Repository codestates-seb/seb40_main_004, pull requests merged in 2022-11, with the labels that each got.

#6 chore : Entity 생성 및 연관관계 매핑 완료
  server/morak_back_end/.gitignore
  server/morak_back_end/build.gradle
  server/morak_back_end/gradle/wrapper/gradle-wrapper.jar
  server/morak_back_end/gradle/wrapper/gradle-wrapper.properties
  server/morak_back_end/gradlew
  server/morak_back_end/gradlew.bat
  server/morak_back_end/settings.gradle
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/MorakBackEndApplication.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Answer.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Article.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/ArticleTag.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Avatar.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Badge.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/BaseTime.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/BookMark.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Category.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Chat.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/ChatIn.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/ChatRoom.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Comment.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Company.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Deposit.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/File.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/GuestBoard.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/InicisLog.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Notification.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/RefreshToken.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Report.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Review.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/ReviewBadge.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Role.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/SkillStack.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Tag.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/User.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/UserRole.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/UserSkillStack.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Vote.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/enums/ArticleStatus.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/enums/BadgeName.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/enums/DepositStatus.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/enums/DomainType.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/enums/Grade.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/enums/JobPayType.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/enums/JobType.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/enums/PStatus.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/enums/PayType.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/enums/PilType.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/enums/RoleName.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/enums/TagName.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/enums/UserStatus.java
  server/morak_back_end/src/main/resources/application.yml
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/MorakBackEndApplicationTests.java
Labels: BE 정희윤, ✔️chore

#16 chore : gitignore 수정 및 의존성 추가
  server/morak_back_end/.gitignore
  server/morak_back_end/build.gradle
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/security/config/AuthenticationManagerConfig.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/security/config/PasswordEncoderConfig.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/security/config/SecurityConfig.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/security/exception/CustomAuthenticationEntryPoint.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/security/exception/InvalidJwtTokenException.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/security/exception/JwtExceptionFilter.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/security/filter/JwtAuthenticationFilter.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/security/oauth/CustomOauth2Service.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/security/oauth/CustomSuccessHandler.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/security/oauth/Oauth2UserDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/security/provider/JwtAuthenticationProvider.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/security/resolver/JwtArgumentResolver.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/security/resolver/RequestUser.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/security/token/JwtAuthenticationToken.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/security/util/JwtTokenUtil.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/security/util/SecurityConstants.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/security/filter/JwtAuthenticationFilterTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/security/provider/JwtAuthenticationProviderTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/security/resolver/JwtArgumentResolverTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/security/util/JwtTokenUtilTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/util/SecurityTestConfig.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/util/SecurityTestConstants.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/util/TestConstants.java
Labels: ✔️chore, [BE] 양은찬

#18 feat : 예외 핸들링 로직 구현
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/exception/BusinessLogicException.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/exception/EmbeddedRedisServerException.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/exception/ErrorCode.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/exception/ErrorResponseEntity.java
Labels: [BE] 양은찬, ✨ Feat

#19 feat : 로직 구현을 위한 각종 dto/상수/메서드 구현 및 테스트
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/AuthDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/DtoValidConstants.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/EmailDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/UserDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Role.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/User.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/UserRole.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/mapper/UserMapper.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/dto/AuthDtoTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/dto/EmailDtoTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/entity/UserTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/mapper/UserMapperTest.java
Labels: [BE] 양은찬, ✨ Feat, ✅ Test

#20 fix : 잘못된 임포트로 인해 정상적으로 빌드할 수 없는 문제 수정
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/security/exception/InvalidJwtTokenException.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/security/oauth/CustomOauth2Service.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/security/oauth/CustomSuccessHandler.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/security/provider/JwtAuthenticationProvider.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/security/resolver/JwtArgumentResolver.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/security/util/JwtTokenUtil.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/dto/AuthDtoTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/dto/EmailDtoTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/mapper/UserMapperTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/security/filter/JwtAuthenticationFilterTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/security/provider/JwtAuthenticationProviderTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/security/resolver/JwtArgumentResolverTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/security/util/JwtTokenUtilTest.java
Labels: [BE] 양은찬, ✅ Test, 🛠 Fix

#21 update, chor : 잘못 지정된 임포트 수정/ 로직 구현을 위한 각종 메서드 및 생성자 추가/ 도커 설정 추가/ 레디스 바이너리 파일 추가
  server/morak_back_end/src/Dockerfile
  server/morak_back_end/src/docker-compose.yml
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/controller/AuthController.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/controller/ExceptionController.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/controller/TestController.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/AuthDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/EmailDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/RefreshToken.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Role.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/User.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/UserRole.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/enums/RoleName.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/mapper/UserMapper.java
  server/morak_back_end/src/main/resources/binary/redis/redis-server-6.0.10-mac-arm64
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/AuthControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/AuthController_Mail_Test.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/TestControllerTest.java
Labels: ✔️chore, [BE] 양은찬, ✨ Feat, ✅ Test, 🛠 Fix

#22 feat : 로그인/회원가입/토큰갱신/로그아웃/메일인증 서비스 로직 구현 및 테스트 코드 작성
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/AuthMailSender.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/AuthMailSenderImpl.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/AuthService.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/AuthController_Mail_Test.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/UserControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/AuthServiceTest.java
Labels: [BE] 양은찬, ✨ Feat, ✅ Test

#23 feat : 회원가입/로그인/토큰갱신/로그아웃용 어댑터 클래스 구현 및 테스트
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/adapter/TokenGenerator.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/adapter/UserPasswordManager.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/adapter/PasswordEncoderTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/adapter/UserPasswordManagerTest.java
Labels: [BE] 양은찬, ✨ Feat, ✅ Test

#24 feat : webConfig, redisConfig, embeddedRedisConfig, testContainer 구현
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/config/EmbeddedRedisConfig.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/config/RedisConfig.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/config/WebConfig.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/config/RedisContainerTest.java
Labels: [BE] 양은찬, ✨ Feat, ✅ Test

#25 feat : 회원가입/로그인/토큰갱신/로그아웃/레디스 테스트용 통합 테스트코드 및 로직 작성
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/RedisRepository.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/RefreshTokenRepository.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/RoleRepository.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/UserRepository.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/UserRoleRepository.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/auth/AuthTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/repository/RedisRepositoryTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/repository/RefreshTokenRepositoryTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/repository/RoleRepositoryTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/repository/UserRepositoryTest.java
Labels: [BE] 양은찬, ✨ Feat, ✅ Test

#26 update : 모든 이넘 필드에 @Enumerated(EnumType.STRING) 작성 및 @Getter 추가
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Article.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Badge.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/BookMark.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Comment.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Company.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Deposit.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/GuestBoard.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/InicisLog.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Notification.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Review.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Role.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Tag.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/User.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Vote.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/enums/ArticleStatus.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/enums/BadgeName.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/enums/DepositStatus.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/enums/DomainType.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/enums/Grade.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/enums/JobPayType.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/enums/JobType.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/enums/PStatus.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/enums/PayType.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/enums/PilType.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/enums/RoleName.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/enums/TagName.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/enums/UserStatus.java
Labels: [BE] 백시온, 🛠 Fix

#41 feat : 패스워드 변경 로직 구현 및 테스트
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/controller/AuthController.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/AuthDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/User.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/exception/ErrorCode.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/AuthService.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/auth/AuthTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/AuthControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/dto/AuthDtoTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/AuthServiceTest.java
Labels: [BE] 양은찬, ✨ Feat, ✅ Test

#49 feat : 패스워드 찾기 로직 구현 및 테스트
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/controller/AuthController.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/UserDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/AuthMailSender.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/AuthService.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/MailSender.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/MailSenderImpl.java
  server/morak_back_end/src/main/resources/application.yml
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/AuthControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/AuthServiceTest.java
Labels: [BE] 양은찬, ✨ Feat, ✅ Test

#51 feat : 회원 탈퇴 로직 및 테스트 코드
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/controller/AuthController.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/AuthDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/User.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/exception/ErrorCode.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/AuthService.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/auth/AuthTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/AuthControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/dto/AuthDtoTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/AuthServiceTest.java
Labels: [BE] 양은찬, ✨ Feat, ✅ Test, Update ❗️

#53 docs : auth controller 문서화 및 restdocs document 설정 추가
  server/morak_back_end/src/docs/asciidoc/index.adoc
  server/morak_back_end/src/main/resources/static/docs/index.html
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/util/ApiDocumentUtils.java
Labels: [BE] 양은찬, ✨ Feat, 📖 Docs

#59 fix : 비밀번호 찾기 시 발급된 임시 비밀번호로 로그인할 수 없던 문제 수정
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/AuthService.java
Labels: [BE] 양은찬, 🛠 Fix

#61 chore : 패키지 설치
  client/.eslintrc.json
  client/.gitignore
  client/.prettierrc
  client/Home.module.css
  client/README.md
  client/globals.css
  client/next-env.d.ts
  client/next.config.js
  client/package-lock.json
  client/package.json
  client/pages/_app.tsx
  client/pages/api/hello.ts
  client/pages/index.tsx
  client/postcss.config.js
  client/public/favicon.ico
  client/public/vercel.svg
  client/styles/Home.module.css
  client/styles/globals.css
  client/tailwind.config.js
  client/tsconfig.json
Labels: ✔️chore, [FE] 박연우

#63 feat : 게시글 등록 수정 삭제 로직 구현 완료 및 테스트 코드 작성 완료했습니다.
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/controller/ArticleController.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/ArticleDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/FileDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/TagDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/UserDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Article.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/ArticleTag.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/File.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Vote.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/enums/ArticleStatus.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/enums/TagName.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/exception/ErrorCode.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/mapper/ArticleMapper.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/mapper/CategoryMapper.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/mapper/FileMapper.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/mapper/TagMapper.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/ArticleRepository.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/CategoryRepository.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/FileRepository.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/TagRepository.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/ArticleService.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/UserService.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/ArticleControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/mapper/ArticleMapperTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/repository/CategoryRepositoryTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/repository/TagRepositoryTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/ArticleServiceTest.java
Labels: [BE] 백시온

#66 fix : 비밀번호 변경의 http 요청 메서드가 post로 되어있던 부분을 모두 patch로 수정
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/controller/AuthController.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/auth/AuthTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/AuthControllerTest.java
Labels: [BE] 양은찬, 🛠 Fix

#67 test : Article Test 상수 클래스와 Repository Role @BeforeEach 메소드 추가
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Role.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/repository/RoleRepositoryTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/util/ArticleTestConstants.java
Labels: [BE] 백시온

#68 refactor : 구현로직 오타 수정및 인자값변경, 테스트 코드 오타수정 모든 테스트 성공 확인
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/controller/ArticleController.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/mapper/ArticleMapper.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/ArticleControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/mapper/ArticleMapperTest.java
Labels: [BE] 백시온, 🛠 Fix

#69 fix, refactor : 역방향 의존성 수정. 불필요한 상수 제거
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/controller/AuthController.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/security/util/SecurityConstants.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/AuthService.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/AuthControllerTest.java
Labels: [BE] 양은찬, 🛠 Fix

#71 update : 이메일 인증 요청 시 데이터베이스에 해당 이메일이 존재한다면 통과할 수 없도록 로직 추가 및 단위테스트 추가
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/controller/AuthController.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/AuthService.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/AuthControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/ArticleServiceTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/AuthServiceTest.java
Labels: [BE] 양은찬, ✅ Test, 🛠 Fix, Update ❗️

#72 chore : tailwind.config 공통 컬러 클래스 추가
  client/tailwind.config.js
Labels: ✔️chore, [FE] 박혜정

#76 test, update : password 찾기 uri 변경 및 테스트 리팩터링
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/controller/AuthController.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/AuthControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/auth_controller/AuthControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/auth_controller/ChangePasswordTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/auth_controller/CheckNicknameTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/auth_controller/DeleteAccountTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/auth_controller/JoinTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/auth_controller/LoginTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/auth_controller/LogoutTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/auth_controller/ReissueTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/auth_controller/SendAuthMailTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/auth_controller/SendEmailForFindPasswordTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/auth_controller/VerifyEmailAuthTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/dto/auth_dto/EmailDtoTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/dto/email_dto/AuthDtoTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/AuthServiceTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/auth_service/AuthServiceTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/auth_service/AuthTemporaryTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/auth_service/ChangePasswordTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/auth_service/CheckDuplicateNicknameTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/auth_service/DeleteAccountTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/auth_service/LoginTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/auth_service/LogoutTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/auth_service/ReissueTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/auth_service/SendAuthenticationEmailForJoinTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/auth_service/SendUserPasswordMailTest.java
Labels: [BE] 양은찬, ✅ Test, 🛠 Fix, Update ❗️

#77 test : 테스트 리팩터링, 레디스 적용 이후 실행불가능하던 테스트들 회생
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/controller/AuthController.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/RedisRepository.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/RedisRepositoryImpl.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/auth/AuthTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/config/ApiDocumentUtils.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/config/RedisRepositoryTestImpl.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/config/SecurityTestConfig.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/ArticleControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/auth_controller/AuthControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/auth_controller/ChangePasswordTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/auth_controller/CheckNicknameTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/auth_controller/DeleteAccountTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/auth_controller/JoinTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/auth_controller/LoginTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/auth_controller/LogoutTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/auth_controller/ReissueTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/auth_controller/SendAuthMailTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/auth_controller/SendEmailForFindPasswordTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/auth_controller/VerifyEmailAuthTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/repository/RedisRepositoryImplTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/security/resolver/JwtArgumentResolverTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/auth_service/AuthServiceTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/auth_service/AuthTemporaryTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/auth_service/JoinUserTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/auth_service/LoginTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/auth_service/LogoutTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/auth_service/ReissueTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/auth_service/SendAuthenticationEmailForFindPwdTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/auth_service/SendAuthenticationEmailForJoinTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/util/SecurityTestConstants.java
Labels: [BE] 양은찬, ✨ Feat, ✅ Test, Update ❗️

#78 feat : 임시 패스워드 발급 로직 구현 및 테스트
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/controller/AuthController.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/AuthService.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/auth_controller/TemporaryPasswordTest.java
Labels: [BE] 양은찬, ✨ Feat, ✅ Test

#79 test, feat : 테스트 리팩터링 및 난수 생성기 추가
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/adapter/AuthMailSender.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/adapter/RandomKeyGenerator.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/adapter/UserPasswordManager.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/User.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/security/util/SecurityConstants.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/MailSenderImpl.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/auth/AuthTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/adapter/RandomKeyGeneratorTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/adapter/UserPasswordManagerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/config/RedisRepositoryTestImpl.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/entity/UserTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/auth_service/AuthServiceTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/auth_service/ChangePasswordTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/auth_service/DeleteAccountTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/auth_service/LoginTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/auth_service/ReissueTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/auth_service/SendAuthenticationEmailForJoinTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/auth_service/SendUserPasswordMailTest.java
Labels: [BE] 양은찬, ✨ Feat, ✅ Test, 🛠 Fix, Update ❗️

#80 update : 투표가 좋아요로 바뀜으로 인해 like 테이블 추가 및 매핑 변경
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Answer.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Article.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/User.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/enums/ArticleStatus.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/enums/JobType.java
Labels: [BE] 양은찬, Update ❗️

#82 feat : ArticleController 통합테스트 등록, 수정, 삭제 완료했습니다.
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/controller/ArticleController.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/FileDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/TagDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Article.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/ArticleTag.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/File.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/User.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/enums/TagName.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/mapper/FileMapper.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/ArticleRepository.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/ArticleTagRepository.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/CategoryRepository.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/FileRepository.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/TagRepository.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/ArticleService.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/article/delete/ArticleDeleteTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/article/update/ArticleUpdateTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/article/upload/ArticleUploadTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/ArticleControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/ArticleServiceTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/util/ArticleTestConstants.java
Labels: [BE] 백시온, ✨ Feat, ✅ Test

#83 chore : Prettier 설정
  client/.prettierrc
  client/pages/_app.tsx
  client/tailwind.config.js
Labels: ✔️chore, 🛠 Fix, Update ❗️, [FE] 박연우

#84 chore : FontAwesome 패키지 설치
  client/package-lock.json
  client/package.json
Labels: ✔️chore, [FE] 박연우

#85 chore : Recoil 초기설정
  client/atoms.ts
  client/pages/_app.tsx
Labels: ✔️chore, [FE] 박연우

#86 style : Editor 컴포넌트 제작, tailwind 및 prettier 재설정
  .gitmessage.txt
  client/components/haseung/Editor.tsx
  client/package-lock.json
  client/pages/_app.tsx
  client/pages/index.tsx
Labels: ✔️chore, 🛠 Fix, [FE] 정하승

#87 fix : tailwind config main-yellow 컬러 오타 수정
  client/tailwind.config.js
Labels: 🛠 Fix, [FE] 박혜정

#89 컴포넌트 export 방식 변경
  client/components/common/Editor.tsx
  client/pages/index.tsx
Labels: ✔️chore, Update ❗️, [FE] 정하승

#88 feat : Header 공통 컴포넌트 생성
  client/atoms.ts
  client/components/common/Header.tsx
  client/components/yeonwoo/BtnDropdown.tsx
  client/components/yeonwoo/BtnLogin.tsx
  client/components/yeonwoo/BtnUser.tsx
  client/components/yeonwoo/Logo.tsx
  client/components/yeonwoo/Nav.tsx
  client/components/yeonwoo/SearchBar.tsx
  client/pages/_app.tsx
  client/pages/dashboard/index.tsx
  client/pages/edit-password/index.tsx
  client/pages/edit-profile/index.tsx
  client/pages/index.tsx
  client/pages/questions/index.tsx
Labels: ✨ Feat, [FE] 박연우

#90 feat : Button 컴포넌트 생성
  client/components/common/Button.tsx
Labels: ✨ Feat, [FE] 박혜정

#92 Footer 컴포넌트 생성
  client/components/common/Footer.tsx
  client/components/hyejung/DeveloperLink.tsx
  client/components/hyejung/MorakLogo.tsx
  client/pages/index.tsx
Labels: ✨ Feat, Update ❗️, [FE] 박혜정

#91 로그인 컴포넌트 제작
  client/components/common/Editor.tsx
  client/components/haseung/Login.tsx
  client/components/haseung/LoginForm.tsx
  client/pages/_app.tsx
Labels: ✨ Feat, [FE] 정하승

#94 fix : fixed 제거 및 map key props 추가
  client/components/common/Footer.tsx
  client/pages/index.tsx
Labels: 🛠 Fix, [FE] 박혜정

#95 stlye : BtnDropdown 스타일 변경
  client/components/yeonwoo/BtnDropdown.tsx
Labels: [FE] 박연우, 💄 Style

#100 feat : 대시보드 구현을 위한 dto 추가 및 테스트 수정, like 테이블 추가
  server/morak_back_end/src/docs/asciidoc/index.adoc
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/ActivityDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/ArticleDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/AvatarDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/ReviewBadgeDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/ReviewDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/UserDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/AnswerLike.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/ArticleLike.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/CategoryRepository.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/adapter/ResponseSimpleUserDtoPasswordManagerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/entity/ResponseSimpleUserDtoTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/mapper/ResponseSimpleUserDtoMapperTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/repository/ResponseSimpleUserDtoRepositoryTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/repository/TagRepositoryTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/auth_service/JoinResponseSimpleUserTestDto.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/auth_service/SendResponseSimpleUserPasswordMailTestDto.java
Labels: [BE] 양은찬, ✨ Feat

#104 질문 컴포넌트 / 코멘트 컴포넌트 생성
  client/components/hyejung/Comment.tsx
  client/components/hyejung/CommentList.tsx
  client/components/hyejung/CreatedDate.tsx
  client/components/hyejung/QuestionContent/BtnBookmark.tsx
  client/components/hyejung/QuestionContent/BtnLike.tsx
  client/components/hyejung/QuestionContent/QuestionContent.tsx
  client/components/hyejung/QuestionContent/QuestionMainText.tsx
  client/components/hyejung/QuestionContent/QuestionTitle.tsx
  client/components/hyejung/QuestionContent/QuestionWriterBtns.tsx
  client/components/hyejung/QuestionContent/QuestionerInfo.tsx
  client/components/hyejung/QuestionContent/TagList.tsx
  client/components/hyejung/TagButton.tsx
  client/components/hyejung/UserNickname.tsx
  client/pages/questions/[article-id].tsx
Labels: ✨ Feat, Update ❗️, [FE] 박혜정

#102 comment 작성 로직 구현
  .github/ISSUE_TEMPLATE/be
  .github/ISSUE_TEMPLATE/pull_request_template.md
  .github/ISSUE_TEMPLATE/데일리-회고-템플릿.md
  .github/ISSUE_TEMPLATE/백엔드-작업-할당-템플릿.md
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/controller/CommentController.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/CommentDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/BookMark.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/CommentRepository.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/CommentService.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/CommentControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/CommentServiceTest.java
Labels: [BE] 정희윤, ✨ Feat, ✅ Test

#107 답변 컴포넌트 생성 및 질문 컴포넌트 수정
  client/components/hyejung/BtnBookmark.tsx
  client/components/hyejung/BtnLike.tsx
  client/components/hyejung/Comment.tsx
  client/components/hyejung/CommentList.tsx
  client/components/hyejung/LikeBookmarkBtns.tsx
  client/components/hyejung/ProfileImage.tsx
  client/components/hyejung/QuestionAnswer.tsx
  client/components/hyejung/QuestionContent/CreatedDate.tsx
  client/components/hyejung/QuestionContent/QuestionContent.tsx
  client/components/hyejung/QuestionContent/QuestionWriterBtns.tsx
  client/components/hyejung/QuestionContent/QuestionerInfo.tsx
  client/components/hyejung/QuestionContent/UserNickname.tsx
  client/components/hyejung/TextArea.tsx
  client/pages/questions/[article-id].tsx
Labels: ✨ Feat, Update ❗️, [FE] 박혜정, 💄 Style

#111 [BE] Comment 작성 로직 통합테스트, DTO테스트 구현 완료
  .github/ISSUE_TEMPLATE/프론트엔드-작업-계획-템플릿.md
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/controller/CommentController.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/AvatarDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/CommentDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/UserDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Article.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Avatar.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Comment.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/User.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/ArticleRepository.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/AvatarRepository.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/CommentService.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/comment/CommentTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/CommentControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/dto/CommentDtoTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/CommentServiceTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/util/CommentTestConstants.java
Labels: [BE] 정희윤, ✨ Feat, ✅ Test, Update ❗️

#112 feat,test : 기존 bookmark 작성, 삭제 로직 재업로드
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/controller/BookmarkController.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/BookmarkDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Bookmark.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/User.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/BookmarkRepository.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/BookmarkService.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/BookmarkTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/BookmarkControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/BookmarkServiceTest.java
Labels: [BE] 정희윤, ✨ Feat, ✅ Test

#108 유저 관련 페이지 마크업 작업 완료
  client/components/common/Editor.tsx
  client/components/haseung/Intro.tsx
  client/components/haseung/LoginForm.tsx
  client/components/haseung/SignUpForm.tsx
  client/package-lock.json
  client/package.json
  client/pages/_app.tsx
  client/pages/authenticationNumber/index.tsx
  client/pages/login/index.tsx
  client/pages/selectStatus/index.tsx
  client/pages/signup/index.tsx
Labels: ✨ Feat, Update ❗️, [FE] 정하승, 💄 Style

#113 fix : 사용하지 않는 라이브러리 제거 (quilljs-markdown)
  client/package-lock.json
  client/package.json
  client/pages/_app.tsx
Labels: 🛠 Fix, [FE] 박혜정

#115 로그인/회원가입 json-server 테스트, Image 태그 관련 버그 수정
  client/components/haseung/LoginForm.tsx
  client/components/haseung/SignUpForm.tsx
  client/components/haseung/SocialLoginBtn.tsx
  client/package-lock.json
  client/package.json
Labels: ✨ Feat, 📖 Docs, ✅ Test, 🛠 Fix, [FE] 정하승

#116 답변 작성 컴포넌트 생성
  client/components/common/Button.tsx
  client/components/hyejung/Comment/Comment.tsx
  client/components/hyejung/Comment/CommentList.tsx
  client/components/hyejung/QuestionAnswer/AnswerEditor.tsx
  client/components/hyejung/QuestionAnswer/QuestionAnswer.tsx
  client/components/hyejung/QuestionContent/QuestionContent.tsx
  client/pages/questions/[article-id].tsx
Labels: ✨ Feat, Update ❗️, [FE] 박혜정

#118 dto 및 편의메서드들 추가 중간 pr
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/config/JpaQuerydslConfiguration.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/controller/AuthController.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/ActivityDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/ArticleDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/AvatarDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/ReviewBadgeDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/TagDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/UserDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Answer.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/AnswerLike.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Article.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Badge.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Calendar.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Category.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Comment.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Review.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/ReviewBadge.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Tag.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/User.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/enums/BadgeName.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/enums/Grade.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/enums/TagName.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/exception/ErrorCode.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/AnswerLikeRepository.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/AnswerRepository.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/ArticleLikeRepository.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/CalendarRepository.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/CommentRepository.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/ReviewBadgeRepository.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/ReviewRepository.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/UserRepository.java
  server/morak_back_end/src/main/resources/application.yml
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/config/JpaQueryFactoryConfig.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/util/TestConstants.java
Labels: [BE] 양은찬, ✨ Feat, ✅ Test

#117 style : Dropdown 위치 수정
  client/components/yeonwoo/BtnDropdown.tsx
Labels: [FE] 박연우, 💄 Style

#121 인증번호 타이머 구현, 커스텀 버튼 적용
  client/components/haseung/AuthenticationTimer.tsx
  client/pages/authenticationNumber/index.tsx
  client/pages/selectStatus/index.tsx
Labels: ✨ Feat, [FE] 정하승, 💄 Style

#125 질문 상세페이지 모킹 서버/통신 로직 추가
  client/.env
  client/components/hyejung/BtnBookmark.tsx
  client/components/hyejung/Comment/Comment.tsx
  client/components/hyejung/Comment/CommentList.tsx
  client/components/hyejung/Comment/TextArea.tsx
  client/components/hyejung/DeveloperLink.tsx
  client/components/hyejung/LikeBookmarkBtns.tsx
  client/components/hyejung/MorakLogo.tsx
  client/components/hyejung/ProfileImage.tsx
  client/components/hyejung/QuestionAnswer/AnswerEditor.tsx
  client/components/hyejung/QuestionAnswer/AnswerMainText.tsx
  client/components/hyejung/QuestionAnswer/QuestionAnswer.tsx
  client/components/hyejung/QuestionContent/CreatedDate.tsx
  client/components/hyejung/QuestionContent/QuestionContent.tsx
  client/components/hyejung/QuestionContent/QuestionMainText.tsx
  client/components/hyejung/QuestionContent/QuestionTitle.tsx
  client/components/hyejung/QuestionContent/QuestionerInfo.tsx
  client/components/hyejung/QuestionContent/TagList.tsx
  client/components/hyejung/QuestionContent/UserNickname.tsx
  client/libs/client.ts
  client/libs/types.ts
  client/libs/useFetch.ts
  client/mocks/browser.ts
  client/mocks/handlers.ts
  client/mocks/index.ts
  client/mocks/server.ts
  client/mocks/types.ts
  client/next.config.js
  client/package-lock.json
  client/package.json
  client/pages/_app.tsx
  client/pages/questions/[article-id].tsx
  client/public/mockServiceWorker.js
Labels: ✔️chore, ✨ Feat, Update ❗️, [FE] 박혜정

#124 refactor : AvatarInfo 에서 Avatar로 디티오 필드명 변경
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/ArticleDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/mapper/ArticleMapper.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/mapper/ArticleMapperTest.java
Labels: [BE] 백시온

#130 [BE] 코멘트 수정 로직 및 테스트 구현
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/controller/CommentController.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/CommentDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/UserDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Comment.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/exception/ErrorCode.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/CommentRepository.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/CommentService.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/comment/CommentTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/comment_controller/PostCommentControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/comment_controller/UpdateCommentControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/dto/CommentDtoTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/CommentServiceTest.java
Labels: [BE] 정희윤, ✨ Feat, ✅ Test

#131 [BE] 사용하지 않는 파일 삭제처리
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/CommentControllerTest.java
Labels: [BE] 정희윤, ✔️chore

#132 merge : simpleResponseAvatar 로 되어있던 필드명 avatar로 변경
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/CommentDto.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/comment/CommentTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/comment_controller/PostCommentControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/comment_controller/UpdateCommentControllerTest.java
Labels: [BE] 백시온

#129 비밀번호 변경 페이지 마크업
  client/components/haseung/EditPasswordForm.tsx
  client/pages/edit-password/index.tsx
Labels: 📖 Docs, [FE] 정하승, 💄 Style

#133 댓글 삭제 로직 구현
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/controller/CommentController.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/CommentService.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/comment/CommentTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/comment_controller/DeleteCommentControllerTest.java
Labels: [BE] 정희윤, ✨ Feat, ✅ Test

#134 merge : category name필드값 String 타입 Enum으로 변경
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/ArticleDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Article.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Bookmark.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Category.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/enums/CategoryName.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/mapper/CategoryMapper.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/ArticleQueryRepositoryImpl.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/CategoryRepository.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/ArticleService.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/EnumValid.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/EnumValidValidator.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/article/get/ArticleGetTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/article/update/ArticleUpdateTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/article/upload/ArticleUploadTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/article_controller/searchArticleTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/mapper/ArticleMapperTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/repository/ArticleQueryRepositoryImplTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/repository/CategoryRepositoryTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/ArticleServiceTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/util/ArticleTestConstants.java
Labels: [BE] 백시온

#135 merge : 전반적인 Article엔티티 관련 로직 수정 및 Category 엔티티 name 필드 타입 이넘타입으로 변경 및 dto에서 enum 타입 필드로 수정
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/TagDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/UserDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Article.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/mapper/FileMapper.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/ArticleQueryRepository.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/ArticleQueryRepositoryImpl.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/ArticleService.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/article/get/ArticleGetTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/article/update/ArticleUpdateTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/article/upload/ArticleUploadTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/article_controller/ArticleControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/article_controller/searchArticleTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/mapper/ArticleMapperTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/repository/BookmarkRepositoryTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/repository/CategoryRepositoryTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/ArticleServiceTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/util/ArticleTestConstants.java
Labels: [BE] 백시온

#136 Answer 등록 api 구현 및 테스트 완료 및 댓글 수정 로직 리턴값 수정
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/controller/AnswerController.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/controller/CommentController.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/AnswerDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Answer.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Article.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/File.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/exception/ErrorCode.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/AnswerService.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/CommentService.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/FileService.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/answer/AnswerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/bookmark/BookmarkTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/answer/PostAnswerControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/comment_controller/UpdateCommentControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/dto/AnswerDtoTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/util/TestConstants.java
Labels: [BE] 정희윤, ✨ Feat, ✅ Test

#141 유저 대시보드 조회 구현 및 테스트
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/controller/UserController.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/ActivityQueryDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/ArticleDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/AvatarDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/BadgeQueryDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/ReviewDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/TagQueryDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/UserDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Article.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/ArticleLike.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/ArticleTag.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/UserQueryRepository.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/UserRepository.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/UserService.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/user/UserTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/user_controller/UserControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/repository/UserRepositoryTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/user_service/UserServiceTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/util/ActivityQueryDtoTestImpl.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/util/BadgeQueryDtoTestImpl.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/util/TagQueryDtoTestImpl.java
Labels: [BE] 양은찬, ✨ Feat, ✅ Test

#138 merge : fileName에서 filename으로 전반적으로 수정 originFileName도 originFilen…
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/AvatarDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Avatar.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/File.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/mapper/ArticleMapper.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/mapper/CommentMapper.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/answer/AnswerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/article/get/ArticleGetTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/comment/CommentTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/answer/PostAnswerControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/article_controller/searchArticleTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/comment_controller/DeleteCommentControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/comment_controller/PostCommentControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/comment_controller/UpdateCommentControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/mapper/ArticleMapperTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/repository/ArticleLikeRepositoryTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/repository/BookmarkRepositoryTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/util/TestConstants.java
Labels: [BE] 백시온

#137 refactor : postAnswer 통합테스트 400 에러 반환 문제 수정
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/answer/AnswerTest.java
Labels: [BE] 정희윤, 🛠 Fix

#140 feat : 메인 페이지 레이아웃(퍼블리싱) 작업
  client/components/yeonwoo/BtnDropdown.tsx
  client/components/yeonwoo/Calendar.tsx
  client/components/yeonwoo/CarouselMain.tsx
  client/components/yeonwoo/CheerUp.tsx
  client/components/yeonwoo/HallOfFame.tsx
  client/components/yeonwoo/ListLately.tsx
  client/next.config.js
  client/package-lock.json
  client/package.json
  client/pages/_app.tsx
  client/pages/index.tsx
Labels: ✨ Feat, [FE] 박연우, 💄 Style

#146 테스트 성공 못하는 부분 수정
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/UserDto.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/user/UserTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/user_controller/UserControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/repository/UserRepositoryTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/user_service/UserServiceTest.java
Labels: [BE] 양은찬, ✅ Test, 🛠 Fix

#144 style : 태그 드롭다운 구현
  client/.eslintrc.json
  client/components/haseung/LoadMoreButton.tsx
  client/components/haseung/QuestionList.tsx
  client/components/haseung/SearchWithTagButton.tsx
  client/components/haseung/Select.tsx
  client/components/haseung/TagSelect.tsx
  client/pages/ask/index.tsx
  client/pages/questions/index.tsx
Labels: ✔️chore, ✨ Feat, 📖 Docs, [FE] 정하승, 💄 Style

#153 회원정보 수정 로직 구현
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/adapter/AuthMailSender.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/controller/AuthController.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/controller/UserController.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/TagDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/UserDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Answer.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Article.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Comment.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/User.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/mapper/UserMapper.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/UserQueryRepository.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/AnswerService.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/ArticleService.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/CommentService.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/EnumValid.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/auth_user_service/AuthService.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/auth_user_service/UserService.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/mail_service/MailSender.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/mail_service/MailSenderImpl.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/auth/AuthTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/user/UserTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/auth_controller/AuthControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/user_controller/DashboardTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/user_controller/UserControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/ArticleServiceTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/CommentServiceTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/auth_service/AuthServiceTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/auth_service/SendAuthenticationEmailForJoinTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/auth_service/SendResponseSimpleUserPasswordMailTestDto.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/user_service/UserServiceTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/user_service/getUserDashboardTest.java
Labels: [BE] 양은찬, ✨ Feat, ✅ Test, Update ❗️

#156 merge : 게시글 답변글 좋아요 머지 합니다.
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/controller/AnswerController.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/controller/ArticleController.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/AnswerDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/ArticleDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/exception/ErrorCode.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/mapper/AnswerMapper.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/mapper/ArticleMapper.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/AnswerLikeRepository.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/AnswerRepository.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/AnswerService.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/ArticleService.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/answer/AnswerPressLikeButton.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/article/get/ArticleGetTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/article/patch/ArticleUpdateTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/article/post/ArticlePressLikeButton.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/article/post/ArticleUploadTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/answer/AnswerControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/article_controller/ArticleControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/article_controller/searchArticleTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/mapper/AnswerMapperTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/mapper/ArticleMapperTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/repository/AnswerLikeRepositoryTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/repository/AnswerRepositoryTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/AnswerServiceTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/ArticleServiceTest.java
Labels: [BE] 백시온

#155 대시보드 페이지 퍼블리싱 작업
  client/atomsYW.ts
  client/components/common/Header.tsx
  client/components/yeonwoo/AsideBot.tsx
  client/components/yeonwoo/AsideMid.tsx
  client/components/yeonwoo/AsideTop.tsx
  client/components/yeonwoo/BtnDropdown.tsx
  client/components/yeonwoo/BtnLogin.tsx
  client/components/yeonwoo/CarouselArticle.tsx
  client/components/yeonwoo/CarouselReview.tsx
  client/components/yeonwoo/Grass.tsx
  client/pages/dashboard/index.tsx
Labels: ✨ Feat, [FE] 박연우, 💄 Style

#157 답변 채택/후원페이지 퍼블리싱
  client/atomsHJ.ts
  client/components/hyejung/BtnBackArticle.tsx
  client/components/hyejung/BtnTag.tsx
  client/components/hyejung/Comment/CommentList.tsx
  client/components/hyejung/Comment/TextArea.tsx
  client/components/hyejung/ProgressBar.tsx
  client/components/hyejung/QuestionContent/TagList.tsx
  client/components/hyejung/ReviewTag.tsx
  client/libs/interfaces.ts
  client/pages/review/completion.tsx
  client/pages/review/index.tsx
  client/pages/review/message.tsx
  client/pages/review/support-morak.tsx
Labels: ✔️chore, ✨ Feat, Update ❗️, [FE] 박혜정

#158 merge : rest docs 작성과 작성하면서 추가적으로 진행한 컨트롤러 / 통합테스트 로직
  server/morak_back_end/src/docs/asciidoc/article.adoc
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/ArticleQueryRepositoryImpl.java
  server/morak_back_end/src/main/resources/static/docs/article.html
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/article/get/ArticleGetTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/answer_controller/AnswerControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/article_controller/ArticleControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/article_controller/searchArticleTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/AnswerServiceTest.java
Labels: [BE] 백시온

#159 태그 스타일 수정
  client/components/haseung/Select.tsx
Labels: ✔️chore, [FE] 정하승, 💄 Style

#161 feat: 개인정보 수정 페이지 퍼블리싱
  client/components/yeonwoo/AsideEditProfile.tsx
  client/components/yeonwoo/EditAvatar.tsx
  client/components/yeonwoo/EditProfile.tsx
  client/pages/edit-profile/index.tsx
Labels: ✨ Feat, [FE] 박연우, 💄 Style

#147 폰트 최적화 설정,회원가입 부분 코드 수정
  client/components/haseung/SignUpForm.tsx
  client/components/haseung/SocialLoginBtn.tsx
  client/pages/_document.tsx
  client/pages/authentication-number/index.tsx
Labels: ✨ Feat, [FE] 정하승, 💄 Style

#163 merge : rest docs 다시 수정해서 올립니다!
  server/morak_back_end/src/docs/asciidoc/article.adoc
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/answer_controller/AnswerControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/article_controller/ArticleControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/article_controller/searchArticleTest.java
Labels: [BE] 백시온

#169 유저 알림 리다이렉트(클릭 조회) 로직 구현 및 테스트
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/controller/NotificationController.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Notification.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/exception/ErrorCode.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/NotificationService.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/notification/NotificationTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/notification_controller/NotificationControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/notification_service/NotificationServiceTest.java
Labels: [BE] 양은찬, ✨ Feat, ✅ Test

#170 merge : 게시글 신고 관련 로직 머지 요청합니다.
  server/morak_back_end/src/docs/asciidoc/article.adoc
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/controller/ArticleController.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/ArticleDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Report.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/enums/ReportReason.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/mapper/ArticleMapper.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/ReportRepository.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/ArticleService.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/article/get/ArticleGetTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/article/post/ReportArticleTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/article_controller/ArticleControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/article_controller/searchArticleTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/mapper/ArticleMapperTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/ArticleServiceTest.java
Labels: [BE] 백시온

#171 feat, test : 유저 알림 삭제 로직 구현, 테스트
  server/morak_back_end/src/docs/asciidoc/user.adoc
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/controller/NotificationController.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/ArticleDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/exception/ErrorCode.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/NotificationService.java
  server/morak_back_end/src/main/resources/static/docs/article.html
  server/morak_back_end/src/main/resources/static/docs/user.html
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/article/post/ReportArticleTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/notification/NotificationTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/notification_controller/NotificationControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/ArticleServiceTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/notification_service/NotificationServiceTest.java
Labels: [BE] 양은찬, ✨ Feat, 📖 Docs, ✅ Test

#177 feat,test : Point / Notification 관리용 클래스들 구현 및 테스트
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/domain/NotificationGenerator.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/domain/NotificationMessage.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/domain/NotificationUri.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/domain/PointCalculator.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Notification.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Review.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/User.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/exception/ErrorCode.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/user/UserQueryRepository.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/ArticleService.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/NotificationService.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/answer/GetAnswersTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/answer/UpdateAnswerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/answer_controller/AnswerControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/domain/NotificationGeneratorTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/domain/NotificationMessageTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/domain/NotificationUriTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/domain/PointCalculatorTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/entity/UserTest.java
Labels: [BE] 양은찬, ✨ Feat, ✅ Test, 🛠 Fix

#179 Feat, Test: 게시글 작성, 좋아요 시 포인트 지급/ 알림 생성 로직 구현 및 테스트
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/controller/AuthController.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/domain/NotificationGenerator.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/domain/NotificationMessage.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/User.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/AnswerService.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/ArticleService.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/CommentService.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/NotificationService.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/answer/AnswerPressLikeButton.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/answer/PostAnswerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/article/delete/ArticleDeleteTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/article/post/ArticlePressLikeButton.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/article/post/ArticleUploadTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/comment/CommentTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/notification/NotificationTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/entity/UserTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/repository/NotificationRepositoryTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/AnswerServiceTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/ArticleServiceTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/CommentServiceTest.java
Labels: [BE] 양은찬, ✨ Feat, ✅ Test, Update ❗️

#178 로그인 기능 구현
  client/atomsHS.ts
  client/components/haseung/LoginForm.tsx
  client/components/haseung/SignUpForm.tsx
  client/next.config.js
  client/package-lock.json
  client/pages/authentication-number/index.tsx
  client/pages/selectStatus/index.tsx
  client/pages/signup-email/index.tsx
  client/pages/signup-status/index.tsx
Labels: ✨ Feat, [FE] 정하승

#181 fix : jwt token에 닉네임 값을 포함하도록 변경
  .idea/.gitignore
  .idea/aws.xml
  .idea/compiler.xml
  .idea/dataSources.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/seb40_main_004.iml
  .idea/uiDesigner.xml
  .idea/vcs.xml
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/controller/AuthController.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/User.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/security/oauth/CustomSuccessHandler.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/security/util/JwtTokenUtil.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/security/util/SecurityConstants.java
  server/morak_back_end/src/main/resources/static/docs/Bookmark.html
  server/morak_back_end/src/main/resources/static/docs/Comment.html
  server/morak_back_end/src/main/resources/static/docs/article.html
  server/morak_back_end/src/main/resources/static/docs/user.html
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/answer/AnswerPressLikeButton.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/answer/PostAnswerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/answer/UpdateAnswerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/article/delete/ArticleDeleteTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/article/get/ArticleGetTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/article/patch/ArticleUpdateTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/article/post/ArticlePressLikeButton.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/article/post/ArticleUploadTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/article/post/ReportArticleTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/auth/AuthTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/bookmark/BookmarkTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/comment/CommentTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/notification/NotificationTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/user/EditUserProfileTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/TestControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/notification_controller/NotificationControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/user_controller/PatchProfileTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/security/util/JwtTokenUtilTest.java
Labels: [BE] 양은찬, 🛠 Fix

#182 유저 데이터 반환하는 로직 추가
  client/atomsHS.ts
  client/components/haseung/LoginForm.tsx
  client/components/haseung/SignUpForm.tsx
  client/package-lock.json
  client/package.json
  client/pages/signup-email/index.tsx
Labels: ✨ Feat, 🛠 Fix, [FE] 정하승

#186 update : 헤더 인증 API 연동
  client/atomsHS.ts
  client/atomsYW.ts
  client/components/common/Header.tsx
  client/components/haseung/LoginForm.tsx
  client/components/yeonwoo/BtnDropdown.tsx
  client/components/yeonwoo/BtnLogin.tsx
  client/components/yeonwoo/BtnUser.tsx
  client/interfaces.ts
  client/next.config.js
Labels: Update ❗️, [FE] 박연우

#187 update : 로그아웃 버튼 클릭시 로그아웃 API 호출
  client/components/yeonwoo/BtnDropdown.tsx
Labels: Update ❗️, [FE] 박연우

#188 인증, 대시보드 조회 버그 수정 및 관련 로직 수정
  server/morak_back_end/build.gradle
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/ArticleDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/AvatarDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/FileDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/UserDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Article.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/ArticleLike.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Avatar.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Category.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/File.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/User.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/mapper/UserMapper.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/user/UserQueryRepository.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/user/UserRepository.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/auth_user_service/AuthService.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/config/RedisRepositoryTestImpl.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/auth_controller/AuthControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/auth_controller/ChangePasswordTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/auth_controller/CheckNicknameTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/auth_controller/DeleteAccountTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/auth_controller/JoinTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/auth_controller/LoginTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/auth_controller/LogoutTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/auth_controller/ReissueTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/auth_controller/SendAuthMailTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/auth_controller/SendEmailForFindPasswordTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/auth_controller/TemporaryPasswordTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/auth_controller/VerifyEmailAuthTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/auth_service/AuthServiceTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/auth_service/JoinResponseSimpleUserTestDto.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/auth_service/ReissueTest.java
Labels: [BE] 양은찬, ✅ Test, 🛠 Fix

#193 update, test : 대시보드 조회 로직 수정 및 테스트 변경
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/config/AwsConfig.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/ActivityDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/UserDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/user/UserQueryRepository.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/auth_user_service/UserService.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/user_controller/DashboardTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/repository/user_repository/UserRepositoryTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/auth_service/JoinResponseSimpleUserDtoTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/user_service/getUserDashboardTest.java
Labels: [BE] 양은찬, ✅ Test, Update ❗️

#194 feat, test : 유저 대시보드 상세 조회용 api 개발 및 테스트
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/controller/UserController.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/ActivityDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/ArticleDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Avatar.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/exception/ErrorCode.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/user/UserQueryRepository.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/auth_user_service/UserService.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/user/GetDashboardTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/user/UserTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/user_controller/RankingTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/user_controller/UserControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/repository/user_repository/UserRepositoryTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/user_service/EditUserProfileTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/user_service/UserServiceTest.java
Labels: [BE] 양은찬, ✨ Feat, ✅ Test, Update ❗️

#189 update : 유저정보 로컬스토리지 관리로 전환
  client/atomsYW.ts
  client/components/common/Header.tsx
  client/components/haseung/LoginForm.tsx
  client/components/yeonwoo/BtnDropdown.tsx
  client/components/yeonwoo/BtnUser.tsx
Labels: Update ❗️, [FE] 박연우

#195 답변 최신순 조회로 로직 수정 변경사항
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Answer.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Article.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/User.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/AnswerService.java
Labels: [BE] 정희윤, 🛠 Fix

#196 feat : Activity Type Enum 추가
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/enums/ActivityType.java
Labels: [BE] 양은찬, ✨ Feat

#197 채택 및 알림 로직 구현 및 테스트 완료
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/controller/ReviewController.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/BadgeDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/ReviewDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Review.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/User.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/exception/ErrorCode.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/BadgeRepository.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/ReviewService.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/review/PostReviewTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/review_controller/Review_Answer_Controller.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/review_controller/Review_User_Controller.java
Labels: [BE] 정희윤, ✨ Feat, ✅ Test, 🛠 Fix

#198 아마존 S3 PreSigned Upload, Delete 구현 및 테스트
  server/morak_back_end/build.gradle
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/controller/AmazonS3Controller.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/JobInfoDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/UserDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/User.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/exception/ErrorCode.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/user/UserQueryRepository.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/AmazonS3StorageService.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/ReviewService.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/auth_user_service/UserService.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/amazon_s3_controller/AmazonS3ControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/amazon_s3_service/AmazonS3StorageServiceTest.java
Labels: [BE] 양은찬, ✨ Feat, ✅ Test, 🛠 Fix, Update ❗️

#201 질문 상세페이지 답변 관련 기능 업데이트
  client/.env
  client/atomsHJ.ts
  client/components/hyejung/AnswerContainer.tsx
  client/components/hyejung/AnswerContent.tsx
  client/components/hyejung/AnswerEditor.tsx
  client/components/hyejung/AnswerMainText.tsx
  client/components/hyejung/BtnBookmark.tsx
  client/components/hyejung/BtnLike.tsx
  client/components/hyejung/BtnTag.tsx
  client/components/hyejung/Comment.tsx
  client/components/hyejung/Comment/CommentList.tsx
  client/components/hyejung/Comment/TextArea.tsx
  client/components/hyejung/CommentList.tsx
  client/components/hyejung/CommentTextArea.tsx
  client/components/hyejung/CreatedDate.tsx
  client/components/hyejung/QuestionAnswer/AnswerEditor.tsx
  client/components/hyejung/QuestionAnswer/AnswerMainText.tsx
  client/components/hyejung/QuestionAnswer/QuestionAnswer.tsx
  client/components/hyejung/QuestionContent.tsx
  client/components/hyejung/TagList.tsx
  client/libs/client.ts
  client/libs/interfaces.ts
  client/libs/useFetchSWR.ts
  client/mocks/browser.ts
  client/mocks/handlers.ts
  client/mocks/index.ts
  client/mocks/server.ts
  client/mocks/types.ts
  client/next.config.js
  client/package-lock.json
  client/package.json
  client/pages/_app.tsx
  client/pages/questions/[articleId].tsx
  client/pages/questions/index.tsx
Labels: ✔️chore, ✨ Feat, Update ❗️, [FE] 박혜정

#200 랭킹 리스트 조회, 단일 랭킹 조회 기능 추가
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/UserDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/user/UserRepository.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/auth_user_service/UserService.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/user/GetDashboardTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/answer_controller/AnswerControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/user_controller/DashboardTest.java
Labels: [BE] 양은찬, ✨ Feat, Update ❗️

#202 fix : 새로고침시 로그인 상태 풀리는 문제 해결
  client/components/common/Header.tsx
Labels: 🛠 Fix, [FE] 박연우

#203 fix : fullCalendar hydration 오류 해결
  client/pages/index.tsx
Labels: 🛠 Fix, [FE] 박연우

#205 Feat : 댓글 로직 완성 및 관련된 게시글, 답변 테스트 코드 수정
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/controller/CommentController.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/AnswerDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/CommentDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Answer.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Article.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Comment.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/CommentRepository.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/CommentService.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/ReviewService.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/answer/GetAnswersTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/answer/PostAnswerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/answer/UpdateAnswerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/comment/CommentTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/review/PostReviewTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/answer_controller/AnswerControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/answer_controller/GetAnswerControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/answer_controller/UpdateAnswerControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/article_controller/searchArticleTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/comment_controller/DeleteCommentOnAnswer_ControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/comment_controller/DeleteCommentOnArticle_ControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/comment_controller/GetCommentsOnAnswer_ControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/comment_controller/GetCommentsOnArticle_ControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/comment_controller/PostCommentOnAnswer_ControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/comment_controller/PostCommentOnArticle_ControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/comment_controller/UpdateCommentOnAnswer_ControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/comment_controller/UpdateCommentOnArticle_ControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/CommentServiceTest.java
Labels: [BE] 정희윤, ✅ Test, 🛠 Fix

#208 feat : 유저의 답변 리스트 조회 로직 추가
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/controller/AnswerController.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/controller/UserController.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/AnswerDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/mapper/AnswerMapper.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/answer/AnswerRepository.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/AnswerService.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/auth_user_service/UserService.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/answer/GetAnswersTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/answer/UpdateAnswerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/user/GetUserAnswerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/answer_controller/GetAnswerControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/answer_controller/PostAnswerControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/answer_controller/UpdateAnswerControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/user_controller/UserAnswerTest.java
Labels: [BE] 정희윤, ✨ Feat, ✅ Test

#209 fix: 답변 컨트롤러 테스트 수정, dto 파일 수정사항 반영
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/AnswerDto.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/answer/GetAnswersTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/answer_controller/GetAnswerControllerTest.java
Labels: [BE] 정희윤, 🛠 Fix

#212 크롤링 로직 구현 및 테스트
  build.gradle
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/crawler/Crawler.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/crawler/JobKoreaCrawler.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/crawler/SeleniumContext.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Job.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/enums/JobType.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/JobRepository.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/repository/JobRepositoryTest.java
Labels: [BE] 양은찬, ✨ Feat, ✅ Test

#213 크롤러 스케줄링 및 설정 변경
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/MorakBackEndApplication.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/crawler/JobKoreaCrawler.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/crawler/SeleniumContext.java
Labels: [BE] 양은찬, Update ❗️

#214 토큰 반환 시 아바타 경로 포함하는 것으로 로직 변경 및 관련 테스트 수정
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/AuthDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/UserDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/mapper/UserMapper.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/schedule/CrawlingScheduler.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/auth_user_service/AuthService.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/user/EditUserProfileTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/auth_controller/JoinTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/auth_controller/LoginTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/auth_controller/ReissueTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/auth_service/LoginTest.java
Labels: [BE] 양은찬, Update ❗️

#215 CI/CD를 위한 머지 요청
  .github/workflows/gradle.yml
  .idea/.gitignore
  .idea/aws.xml
  .idea/compiler.xml
  .idea/dataSources.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/seb40_main_004.iml
  .idea/uiDesigner.xml
  .idea/vcs.xml
  appspec.yml
  build.gradle
  deploy.sh
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: [BE] 백시온

#216 채용 정보 달력 조회 관련 로직 구현 및 테스트
  server/morak_back_end/src/docs/asciidoc/calendar.adoc
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/controller/CalendarController.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/crawler/SeleniumContext.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/JobInfoDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/JobQueryRepository.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/schedule/CrawlingScheduler.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/CalendarService.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/calendar/CalendarTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/calendar_controller/CalenderControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/repository/JobQueryRepositoryTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/CalendarServiceTest.java
Labels: [BE] 양은찬, ✨ Feat, ✅ Test

#217 merge : 깃헙 액션을 위한 테스트 코드 @EnabledIfEnvironmentVariable 어노테이션 등록
  .github/ISSUE_TEMPLATE/be
  .github/ISSUE_TEMPLATE/pull_request_template.md
  .github/ISSUE_TEMPLATE/데일리-회고-템플릿.md
  .github/ISSUE_TEMPLATE/백엔드-작업-할당-템플릿.md
  .github/ISSUE_TEMPLATE/프론트엔드-작업-계획-템플릿.md
  .github/workflows/gradle.yml
  .idea/.gitignore
  .idea/aws.xml
  .idea/compiler.xml
  .idea/dataSources.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/seb40_main_004.iml
  .idea/uiDesigner.xml
  .idea/vcs.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/crawler/SeleniumContext.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/answer/AnswerPressLikeButton.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/answer/GetAnswersTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/answer/PostAnswerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/answer/UpdateAnswerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/article/delete/ArticleDeleteTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/article/get/ArticleGetTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/article/patch/ArticleUpdateTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/article/post/ArticlePressLikeButton.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/article/post/ArticleUploadTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/article/post/ReportArticleTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/auth/AuthTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/bookmark/BookmarkTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/comment/CommentTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/notification/NotificationTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/review/PostReviewTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/user/EditUserProfileTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/user/GetDashboardTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/user/GetUserAnswerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/user/UserTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/user/getUserRankTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/mapper/AnswerMapperTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/mapper/ArticleMapperTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/repository/AnswerLikeRepositoryTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/repository/AnswerRepositoryTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/repository/ArticleLikeRepositoryTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/repository/ArticleQueryRepositoryImplTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/repository/BookmarkRepositoryTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/repository/CategoryRepositoryTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/repository/JobRepositoryTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/repository/NotificationRepositoryTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/repository/RedisRepositoryImplTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/repository/RefreshTokenRepositoryTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/repository/ResponseSimpleUserDtoRepositoryTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/repository/RoleRepositoryTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/repository/TagRepositoryTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/repository/user_repository/UserRepositoryTest.java
  settings.gradle
Labels: [BE] 백시온

#219 chore : CI/CD를 위한 파일 수정 작업
  .github/workflows/gradle.yml
Labels: [BE] 백시온

#220 refactor : @EnabledIfEnvironmentVariable어노테이션 등록
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/TestControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/calendar/CalendarTest.java
Labels: [BE] 백시온

#221 Merge 서버 메인 머지
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/TestControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/calendar/CalendarTest.java
Labels: [BE] 백시온

#222 refactor : @EnabledIfEnvironmentVariable어노테이션 등록
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/repository/JobQueryRepositoryTest.java
Labels: [BE] 백시온

#223 서버 메인 머지
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/repository/JobQueryRepositoryTest.java
Labels: [BE] 백시온

#224 chore : 깃헙액션 chromedriver 설치 로직 추가
  .github/workflows/gradle.yml
Labels: [BE] 백시온

#225 서버 메인 머지
  .github/workflows/gradle.yml
Labels: [BE] 백시온

#227 fix : CommentDto answerId로 로직 수정
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/CommentDto.java
Labels: [BE] 정희윤, 🛠 Fix, Update ❗️

#229 fix : 로그인 시 리프레시 토큰을 정상 반환하도록 변경/ 리졸버에서 Authorization이 null이여도 통과하도록 변경
  .idea/dataSources.xml
  .idea/gradle.xml
  .idea/misc.xml
  server/morak_back_end/build.gradle
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/domain/TokenGenerator.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/User.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/security/resolver/JwtArgumentResolver.java
  server/morak_back_end/src/main/resources/static/docs/Bookmark.html
  server/morak_back_end/src/main/resources/static/docs/article.html
  server/morak_back_end/src/main/resources/static/docs/user.html
Labels: [BE] 양은찬, 🛠 Fix

#228 fix : Answer의 comment preview npe 해결
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/CommentDto.java
Labels: [BE] 정희윤, 🛠 Fix, Update ❗️

#230 질문 작성 기능 구현
  client/atomsHS.ts
  client/components/common/Editor.tsx
  client/components/haseung/LoginForm.tsx
  client/components/haseung/SignUpForm.tsx
  client/pages/ask/index.tsx
  client/pages/signup-email/index.tsx
  client/pages/signup-status/index.tsx
Labels: ✨ Feat, [FE] 정하승

#232 fix : 답변, 게시글 삭제 시 코멘트 삭제 로직 구현
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Answer.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Article.java
Labels: [BE] 정희윤, 🛠 Fix

#234 게시글 검색 로직 수정 머지 요청
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/article/ArticleQueryRepositoryImpl.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/repository/ArticleQueryRepositoryImplTest.java
Labels: [BE] 백시온

#235 refactor : 크롤러 관련 클래스/인터페이스 리팩터링
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/crawler/Crawler.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/crawler/JobKoreaConstant.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/crawler/JobKoreaCrawler.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/enums/BadgeName.java
Labels: [BE] 양은찬, refactor

#236 update : article, review 작성 시 배지 및 태그를 id가 아닌 이름(상수)로 조회하도록 변경
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/BadgeRepository.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/ArticleService.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/ReviewService.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/article/post/ArticleUploadTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/ArticleServiceTest.java
Labels: [BE] 양은찬, Update ❗️

#238 refactor : review 채택 로직의 포인트 에러코드 400 -->422 로 수정 반영
  server/morak_back_end/src/docs/asciidoc/review.adoc
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/exception/ErrorCode.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/ReviewService.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/review_controller/Review_Answer_Controller.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/review_controller/Review_User_Controller.java
Labels: [BE] 정희윤, ✅ Test, Update ❗️

#246 태그 드롭다운 기능 구현 완료
  client/components/common/Editor.tsx
  client/components/haseung/SearchWithTagButton.tsx
  client/components/haseung/Select.tsx
  client/components/haseung/TagSelect.tsx
Labels: ✨ Feat, Update ❗️, [FE] 정하승

#247 질문,답변 코멘트 CRUD, 좋아요 / 북마크 API 연결
  client/atomsHJ.ts
  client/components/hyejung/AnswerContent.tsx
  client/components/hyejung/BtnBookmark.tsx
  client/components/hyejung/BtnLike.tsx
  client/components/hyejung/Comment.tsx
  client/components/hyejung/CommentContainer.tsx
  client/components/hyejung/CommentTextArea.tsx
  client/components/hyejung/CreatedDate.tsx
  client/components/hyejung/EditCommentTextArea.tsx
  client/components/hyejung/ProfileImage.tsx
  client/components/hyejung/QuestionContent.tsx
  client/components/hyejung/QuestionMainText.tsx
  client/libs/interfaces.ts
  client/libs/uploadS3.ts
  client/pages/questions/[articleId].tsx
Labels: ✔️chore, Update ❗️, [FE] 박혜정

#249 fix : 대시보드 조회 시 삭제된 글이 조회되는 문제 수정
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/user/UserQueryRepository.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/repository/user_repository/UserRepositoryTest.java
Labels: 🛠 Fix

#248 fix : article 삭제 시 예외처리 추가
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/ArticleService.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/article/get/ArticleGetTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/article/patch/ArticleUpdateTest.java
Labels: [BE] 정희윤, ✅ Test, 🛠 Fix, Update ❗️

#252 일반 게시글 조회시 삭제된 글이 조회되는 문제 수정
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/article/ArticleQueryRepositoryImpl.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/review/PostReviewTest.java
Labels: [BE] 양은찬, 🛠 Fix

#253 refactor : 게시물 상태확인 로직 테스트 코드 추가 및 dto 유효성 검사기준 통일
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/ArticleDto.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/article_controller/ArticleControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/article_controller/Delete_ArticleController.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/article_controller/Update_ArticleController.java
Labels: [BE] 정희윤, ✅ Test, 🛠 Fix

#254 feat : 답변 채택 기능 구현중
  client/components/hyejung/BtnBackArticle.tsx
  client/components/hyejung/QuestionContent.tsx
  client/components/hyejung/ReviewTag.tsx
  client/pages/review/completion.tsx
  client/pages/review/index.tsx
  client/pages/review/message.tsx
  client/pages/review/support-morak.tsx
Labels: ✨ Feat, [FE] 박혜정

#256 fix : eslint 에러 수정
  client/.eslintrc.json
Labels: 🛠 Fix, [FE] 박연우

#257 프론트 서버 1차 배포를 위한 수정 (1)
  client/.eslintrc.json
  client/components/hyejung/BtnBackArticle.tsx
  client/components/hyejung/QuestionContent.tsx
  client/components/hyejung/ReviewTag.tsx
  client/pages/review/completion.tsx
  client/pages/review/index.tsx
  client/pages/review/message.tsx
  client/pages/review/support-morak.tsx
Labels: 🛠 Fix, [FE] 박연우

#259 스타일 자잘한거 수정
  client/components/common/Editor.tsx
  client/components/haseung/LoginForm.tsx
  client/components/haseung/QuestionList.tsx
  client/components/haseung/Select.tsx
  client/pages/questions/index.tsx
Labels: ✔️chore, ✨ Feat, Update ❗️, [FE] 정하승, 💄 Style

#260 feat : 유저 기본 등급 가지도록 수정 / 등급 관련 메서드 추가
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/User.java
Labels: [BE] 양은찬, ✨ Feat, Update ❗️

#261 update : grade 상수 추가
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/enums/Grade.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/comment/CommentTest.java
Labels: [BE] 양은찬, Update ❗️

#262 log 확인 요청 및 게시글 검색 로직 수정
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/controller/ArticleController.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/controller/BookmarkController.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/AnswerDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/ArticleDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/BookmarkDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Article.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/article/ArticleQueryRepositoryImpl.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/ArticleService.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/article/get/ArticleGetTest.java
Labels: [BE] 백시온

#263 update : 메인 페이지 항목 클릭시 관련 페이지 연결
  client/components/yeonwoo/HallOfFame.tsx
  client/components/yeonwoo/ListLately.tsx
Labels: ✨ Feat, Update ❗️, [FE] 박연우

#264 update : 나의 질문/ 나의 답변/ 북마크 클릭시 글 상세 페이지 연결
  client/components/yeonwoo/CarouselAnswers.tsx
  client/components/yeonwoo/CarouselArticle.tsx
  client/components/yeonwoo/CarouselBookmarks.tsx
Labels: ✨ Feat, Update ❗️, [FE] 박연우

#270 fix : 유저의 아바타가 없을 때 헤더 아바타 이미지 적용 오류 해결
  client/atomsYW.ts
  client/components/yeonwoo/BtnUser.tsx
Labels: 🛠 Fix, [FE] 박연우

#272 배포 : 글 작성 버튼, 헤더 아바타 에러 해결, 메인 페이지/대시보드 항목 클릭시 해당 페이지 연결
  client/atomsYW.ts
  client/components/common/Editor.tsx
  client/components/haseung/LoginForm.tsx
  client/components/haseung/QuestionList.tsx
  client/components/haseung/Select.tsx
  client/components/yeonwoo/BtnUser.tsx
  client/components/yeonwoo/CarouselAnswers.tsx
  client/components/yeonwoo/CarouselArticle.tsx
  client/components/yeonwoo/CarouselBookmarks.tsx
  client/components/yeonwoo/HallOfFame.tsx
  client/components/yeonwoo/ListLately.tsx
  client/pages/questions/index.tsx
Labels: ✨ Feat, 🛠 Fix, Update ❗️, [FE] 박연우

#273 chore : deploy.sh 로직 변경
  deploy.sh
Labels: [BE] 백시온

#269 게시글 서비스 로직 메서드 수정
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/ArticleService.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/article/post/ArticleUploadTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/ArticleServiceTest.java
Labels: [BE] 백시온

#275 update : 응원하기 버튼 클릭시 페이지 연결
  client/components/yeonwoo/AsideTop.tsx
Labels: ✨ Feat, Update ❗️, [FE] 박연우

#276 dev/server 깃헙액션 등록
  .github/workflows/gradle.yml
  appspec.yml
  deploy.sh
Labels: [BE] 백시온

#277 fix, update, test : 유저 등급 추가, 메서드 추가, 관련 테스트 추가, 버그 수정
  server/morak_back_end/build.gradle
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Deposit.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/User.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/entity/UserTest.java
Labels: [BE] 양은찬, ✨ Feat, ✅ Test, 🛠 Fix

#278 test : 유저 등급 변경으로 인해 실패하는 테스트 수정
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/comment/CommentTest.java
Labels: [BE] 양은찬, 🛠 Fix
