Repository codestates-seb/seb40_main_004, pull requests merged in 2022-12, with the labels that each got.

#291 게시글 서비스 로직 리펙터링과 답글 이미지 첨부하면 업로드 안되는 오류 해결
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/AnswerLike.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/ArticleLike.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/AnswerService.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/ArticleService.java
Labels: [BE] 백시온

#294 로그인, 회원가입 ui 및 alert 수정했습니다.
  client/components/common/Footer.tsx
  client/components/haseung/Intro.tsx
  client/components/haseung/LoginForm.tsx
  client/components/haseung/SignUpForm.tsx
  client/components/haseung/SocialLoginBtn.tsx
  client/pages/login/index.tsx
  client/pages/signup-email/index.tsx
  client/pages/signup-status/index.tsx
  client/pages/signup/index.tsx
Labels: [FE] 박혜정, 💄 Style

#289 update : 비밀번호 변경 성공시 alert 출력
  client/components/yeonwoo/EditProfile.tsx
Labels: [FE] 박연우

#295 update : 답변 채택, 응원/후원 하기, 로그인/회원가입 UI
  client/atomsHJ.ts
  client/components/common/Footer.tsx
  client/components/haseung/Intro.tsx
  client/components/haseung/LoginForm.tsx
  client/components/haseung/SignUpForm.tsx
  client/components/haseung/SocialLoginBtn.tsx
  client/components/hyejung/AnswerContainer.tsx
  client/components/hyejung/AnswerContent.tsx
  client/components/hyejung/AnswerEditor.tsx
  client/components/hyejung/BtnBackArticle.tsx
  client/components/hyejung/BtnBookmark.tsx
  client/components/hyejung/BtnLike.tsx
  client/components/hyejung/QuestionContent.tsx
  client/components/hyejung/ReviewTag.tsx
  client/components/hyejung/UserNickname.tsx
  client/components/yeonwoo/AsideTop.tsx
  client/components/yeonwoo/EditProfile.tsx
  client/libs/getIsFromDashboard.ts
  client/pages/edit-password/index.tsx
  client/pages/edit-profile/index.tsx
  client/pages/login/index.tsx
  client/pages/questions/[articleId].tsx
  client/pages/review/completion.tsx
  client/pages/review/index.tsx
  client/pages/review/message.tsx
  client/pages/review/support-morak.tsx
  client/pages/signup-email/index.tsx
  client/pages/signup-status/index.tsx
  client/pages/signup/index.tsx
Labels: ✨ Feat, 🛠 Fix, Update ❗️, [FE] 박연우, 💄 Style

#293 fix, feat, test : 크롤러 방지 필터 설정 / 이미지 업로드 수정 시 버그 수정 및 관련 테스트 / user 탈퇴 로직 변경 및 테스트 수정
  server/morak_back_end/src/docs/asciidoc/article.adoc
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/controller/AuthController.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/controller/UserController.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/User.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/enums/UserStatus.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/exception/ErrorCode.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/article/ArticleQueryRepositoryImpl.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/security/config/AuthenticationManagerConfig.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/security/exception/ExceptionFilter.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/security/filter/CrawlerFilter.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/security/util/SecurityConstants.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/AmazonS3StorageService.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/AnswerService.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/ArticleService.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/auth_user_service/AuthService.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/auth_user_service/UserService.java
  server/morak_back_end/src/main/resources/static/docs/Bookmark.html
  server/morak_back_end/src/main/resources/static/docs/article.html
  server/morak_back_end/src/main/resources/static/docs/auth.html
  server/morak_back_end/src/main/resources/static/docs/user.html
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/TestControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/answer/GetAnswersTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/article/get/ArticleGetTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/article/patch/ArticleUpdateTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/auth/AuthTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/calendar/CalendarTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/notification/NotificationTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/point/GetPointTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/user/GetDashboardTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/user/GetUserAnswerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/user/UserTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/user/getUserRankTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/security/filter/CrawlerFilterTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/security/filter/ExceptionFilterTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/amazon_s3_service/AmazonS3StorageServiceTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/user_service/getUserDashboardTest.java
Labels: [BE] 양은찬, ✨ Feat, ✅ Test, 🛠 Fix

#297 oauth 카카오 계정용 코드 추가 및 리팩터링
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/domain/RandomKeyGenerator.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/User.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/security/oauth/CustomOauth2Service.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/security/oauth/CustomSuccessHandler.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/security/oauth/Oauth2UserDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/security/util/SecurityConstants.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/auth_user_service/AuthService.java
Labels: [BE] 양은찬, ✨ Feat, refactor

#292 질문 리스트 조회 기능 구현
  client/components/haseung/QuestionList.tsx
  client/libs/interfaces.ts
  client/pages/questions/index.tsx
Labels: ✨ Feat, Update ❗️, [FE] 정하승, 💄 Style

#301 feat : 성능 측정을 위한 로깅 기능 구현
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/config/LoggingConfig.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/interceptor/PerformanceLoggingInterceptor.java
Labels: [BE] 양은찬, ✨ Feat

#302 랭킹 조회시 N+1 문제 해결 및 관련 로직 수정
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/UserDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/interceptor/PerformanceLoggingInterceptor.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/user/UserQueryRepository.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/auth_user_service/UserService.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/repository/user_repository/UserRepositoryTest.java
Labels: [BE] 양은찬, 🛠 Fix, Update ❗️

#290 update : 헤더 드롭다운 모락 조회 api 연결
  client/components/yeonwoo/BtnDropdown.tsx
Labels: ✨ Feat, Update ❗️, [FE] 박연우

#304 refactor : 유저 답변 조회 로직 리팩터링
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/controller/UserController.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/UserDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/mapper/UserMapper.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/answer/AnswerQueryRepository.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/auth_user_service/UserService.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/article/post/ArticleUploadTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/user_controller/UserPointTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/mapper/AnswerMapperTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/mapper/UserMapperTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/repository/answer_repository/AnswerQueryRepositoryTest.java
Labels: [BE] 정희윤, ✨ Feat, ✅ Test

#310 대시보드에서 등급 이모지로 표시, axios -> axios 인스턴스 client 로 변경, style 오류 수정
  client/atomsYW.ts
  client/components/yeonwoo/AsideBot.tsx
  client/components/yeonwoo/AsideMid.tsx
  client/components/yeonwoo/AsideTop.tsx
  client/components/yeonwoo/BtnUser.tsx
  client/components/yeonwoo/CarouselAnswers.tsx
  client/components/yeonwoo/CarouselArticle.tsx
  client/components/yeonwoo/CarouselBookmarks.tsx
  client/components/yeonwoo/CarouselReview.tsx
  client/components/yeonwoo/EditProfile.tsx
  client/components/yeonwoo/HallOfFame.tsx
  client/components/yeonwoo/ListLately.tsx
  client/interfaces.ts
  client/libs/changeGradeEmoji.ts
  client/pages/dashboard/[userId]/index.tsx
Labels: ✨ Feat, 🛠 Fix, [FE] 박연우, 💄 Style

#312 랭킹 조회 쿼리 수정
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/user/UserQueryRepository.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/AnswerService.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/auth_user_service/UserService.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/repository/user_repository/UserRepositoryTest.java
Labels: [BE] 양은찬

#306 update : 게시글 리스트 페이지 UI 수정 및 페이지네이션 적용
  client/atomsHJ.ts
  client/components/haseung/Pagination.tsx
  client/components/haseung/QuestionList.tsx
  client/libs/interfaces.ts
  client/pages/questions/index.tsx
Labels: Update ❗️, [FE] 박혜정, 💄 Style

#311 fix : 함수명 오류 수정
  client/libs/changeGradeEmoji.ts
Labels: 🛠 Fix, [FE] 박연우

#313 글목록 컴포넌트 메인 브랜치 merge
  client/atomsHJ.ts
  client/atomsYW.ts
  client/components/haseung/Pagination.tsx
  client/components/haseung/QuestionList.tsx
  client/components/yeonwoo/AsideBot.tsx
  client/components/yeonwoo/AsideMid.tsx
  client/components/yeonwoo/AsideTop.tsx
  client/components/yeonwoo/BtnDropdown.tsx
  client/components/yeonwoo/BtnUser.tsx
  client/components/yeonwoo/CarouselAnswers.tsx
  client/components/yeonwoo/CarouselArticle.tsx
  client/components/yeonwoo/CarouselBookmarks.tsx
  client/components/yeonwoo/CarouselReview.tsx
  client/components/yeonwoo/EditProfile.tsx
  client/components/yeonwoo/HallOfFame.tsx
  client/components/yeonwoo/ListLately.tsx
  client/interfaces.ts
  client/kakaoinit.ts
  client/libs/changeGradeEmoji.ts
  client/libs/client.ts
  client/libs/interfaces.ts
  client/pages/_document.tsx
  client/pages/dashboard/[userId]/index.tsx
  client/pages/questions/index.tsx
  client/react-app-env.d.ts
Labels: ✨ Feat, 🛠 Fix, [FE] 박연우, 💄 Style

#314 build : application.yml 수정
  server/morak_back_end/src/main/resources/application.yml
Labels: [BE] 백시온

#315 Docs : API 통합본 초안
  server/morak_back_end/src/docs/asciidoc/Morakmorak_API.adoc
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/answer/AnswerQueryRepository.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/repository/answer_repository/AnswerQueryRepositoryTest.java
Labels: [BE] 정희윤, 📖 Docs

#318 fix : 게시글 검색 누락된 return 추가
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/article/ArticleQueryRepositoryImpl.java
Labels: [BE] 백시온

#319 feat : 게시글 검색 조건 추가
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/article/ArticleQueryRepositoryImpl.java
Labels: [BE] 백시온

#316 아바타 수정/삭제 기능 추가, 드롭다운 width 조정
  client/atomsYW.ts
  client/components/common/Header.tsx
  client/components/yeonwoo/AsideTop.tsx
  client/components/yeonwoo/BtnDropdown.tsx
  client/components/yeonwoo/BtnUser.tsx
  client/components/yeonwoo/EditAvatar.tsx
  client/components/yeonwoo/EditProfile.tsx
  client/interfaces.ts
  client/pages/dashboard/[userId]/answers.tsx
  client/pages/dashboard/[userId]/bookmarks.tsx
  client/pages/dashboard/[userId]/index.tsx
Labels: ✨ Feat, Update ❗️, [FE] 박연우, 💄 Style

#320 main : 아바타 수정/삭제, 헤어 드롭다운 width 수정
  client/atomsYW.ts
  client/components/common/Header.tsx
  client/components/yeonwoo/AsideTop.tsx
  client/components/yeonwoo/BtnDropdown.tsx
  client/components/yeonwoo/BtnUser.tsx
  client/components/yeonwoo/EditAvatar.tsx
  client/components/yeonwoo/EditProfile.tsx
  client/interfaces.ts
  client/pages/dashboard/[userId]/answers.tsx
  client/pages/dashboard/[userId]/bookmarks.tsx
  client/pages/dashboard/[userId]/index.tsx
Labels: ✨ Feat, Update ❗️, [FE] 박연우, 💄 Style

#325 feat : 유저의 답변 조회 dto에 article id 추가
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/AnswerDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/mapper/AnswerMapper.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/auth_user_service/UserService.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/user/GetUserAnswerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/user_controller/UserAnswerTest.java
Labels: [BE] 정희윤, ✨ Feat, ✅ Test

#322 질문 리스트 페이지 : 검색 / 정렬기능 구현
  client/components/haseung/LoadMoreButton.tsx
  client/components/haseung/Pagination.tsx
  client/components/haseung/QuestionList.tsx
  client/components/haseung/SearchWithTagButton.tsx
  client/pages/questions/[articleId].tsx
  client/pages/questions/index.tsx
Labels: ✔️chore, ✨ Feat, 🛠 Fix, Update ❗️, [FE] 박혜정, 💄 Style

#323 글 작성 시 로딩 상태 표시
  client/components/common/Editor.tsx
Labels: ✨ Feat, [FE] 정하승

#324 자잘한 버그 및 스타일 수정
  client/components/yeonwoo/AsideBot.tsx
  client/components/yeonwoo/AsideMid.tsx
  client/components/yeonwoo/AsideTop.tsx
  client/components/yeonwoo/CarouselAnswers.tsx
  client/components/yeonwoo/CarouselArticle.tsx
  client/components/yeonwoo/CarouselBookmarks.tsx
  client/components/yeonwoo/EditProfile.tsx
  client/components/yeonwoo/ListLately.tsx
  client/components/yeonwoo/Logo.tsx
  client/libs/changeTagPrettier.ts
  client/pages/_document.tsx
  client/pages/dashboard/[userId]/answers.tsx
Labels: 🛠 Fix, Update ❗️, [FE] 박연우, 💄 Style

#328 질문 상세페이지 ui 수정
  client/components/hyejung/AnswerContent.tsx
  client/components/hyejung/AnswerEditor.tsx
  client/components/hyejung/AnswerMainText.tsx
  client/components/hyejung/CommentTextArea.tsx
  client/components/hyejung/QuestionMainText.tsx
  client/components/hyejung/UserNickname.tsx
  client/components/yeonwoo/CarouselMain.tsx
  client/libs/elapsedTime.ts
  client/public/morak-main-1.png
  client/public/morak-main-2.png
  client/public/morak-main-3.png
Labels: 🛠 Fix, [FE] 박혜정, 💄 Style

#329 update : 타이틀 길이에 따라 보이는 형태 수정
  client/components/yeonwoo/ListLately.tsx
Labels: 🛠 Fix, Update ❗️, [FE] 박연우

#330 main : 자잘한 버그 수정, 검색/정렬, 메인 페이지 캐러셀 이미지 추가
  client/components/common/Editor.tsx
  client/components/haseung/LoadMoreButton.tsx
  client/components/haseung/Pagination.tsx
  client/components/haseung/QuestionList.tsx
  client/components/haseung/SearchWithTagButton.tsx
  client/components/hyejung/AnswerContent.tsx
  client/components/hyejung/AnswerEditor.tsx
  client/components/hyejung/AnswerMainText.tsx
  client/components/hyejung/CommentTextArea.tsx
  client/components/hyejung/QuestionMainText.tsx
  client/components/hyejung/UserNickname.tsx
  client/components/yeonwoo/AsideBot.tsx
  client/components/yeonwoo/AsideMid.tsx
  client/components/yeonwoo/AsideTop.tsx
  client/components/yeonwoo/CarouselAnswers.tsx
  client/components/yeonwoo/CarouselArticle.tsx
  client/components/yeonwoo/CarouselBookmarks.tsx
  client/components/yeonwoo/CarouselMain.tsx
  client/components/yeonwoo/EditProfile.tsx
  client/components/yeonwoo/HallOfFame.tsx
  client/components/yeonwoo/ListLately.tsx
  client/components/yeonwoo/Logo.tsx
  client/libs/changeGradeEmoji.ts
  client/libs/changeTagPrettier.ts
  client/libs/elapsedTime.ts
  client/pages/_document.tsx
  client/pages/dashboard/[userId]/answers.tsx
  client/pages/questions/[articleId].tsx
  client/pages/questions/index.tsx
  client/public/morak-main-1.png
  client/public/morak-main-2.png
  client/public/morak-main-3.png
Labels: ✨ Feat, 🛠 Fix, Update ❗️, [FE] 박연우

#327 merge : 게시글 등록 로직 및 테스트 전체적으로 수정
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/controller/ArticleController.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/mapper/ArticleMapper.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/ArticleService.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/CategoryService.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/FileService.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/TagService.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/article_controller/ArticleControllerTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/mapper/ArticleMapperTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/ArticleServiceTest.java
Labels: [BE] 백시온

#331 fix : 유저 아이디로 배지가 조회되지 않던 문제 수정
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/user/UserRepository.java
Labels: [BE] 양은찬, 🛠 Fix

#332 게시글 수정 로직 및 테스트 완료
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/controller/ArticleController.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/TagDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Article.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/ArticleTag.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/mapper/ArticleMapper.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/article/ArticleRepository.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/ArticleService.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/article_controller/Update_ArticleController.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/mapper/ArticleMapperTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/ArticleServiceTest.java
Labels: [BE] 백시온

#337 유저가 탈퇴시에도 로그인되는 문제 수정 / oauth2 로그인 관련 버그 수정
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/User.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/exception/ErrorCode.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/security/config/SecurityConfig.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/security/oauth/CustomSuccessHandler.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/security/oauth/Oauth2UserDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/auth_user_service/AuthService.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/entity/UserTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/auth_service/AuthServiceTest.java
Labels: [BE] 양은찬, ✅ Test, 🛠 Fix

#336 질문 수정 기능 구현 / 태그 선택 드롭다운 수정
  client/atomsHJ.ts
  client/components/common/Editor.tsx
  client/components/haseung/Select.tsx
  client/components/hyejung/QuestionContent.tsx
Labels: ✨ Feat, 🛠 Fix, [FE] 박혜정, 💄 Style

#334 회원 탈퇴
  client/components/yeonwoo/AsideEditProfile.tsx
  client/components/yeonwoo/EditProfile.tsx
  client/pages/membership-withdrawal/index.tsx
Labels: ✨ Feat, [FE] 박연우

#335 탈퇴한 유저의 대시보드 접속시 에러 핸들링
  client/components/yeonwoo/AsideTop.tsx
  client/pages/dashboard/[userId]/answers.tsx
  client/pages/dashboard/[userId]/bookmarks.tsx
  client/pages/dashboard/[userId]/index.tsx
Labels: ✨ Feat, Update ❗️, [FE] 박연우

#333 상단 헤더 검색 기능
  client/atomsYW.ts
  client/components/yeonwoo/SearchBar.tsx
  client/pages/questions/index.tsx
Labels: ✨ Feat, [FE] 박연우

#338 main : 회원탈퇴, 게시글 수정, 상단 헤더 검색
  client/atomsHJ.ts
  client/atomsYW.ts
  client/components/common/Editor.tsx
  client/components/haseung/Select.tsx
  client/components/hyejung/QuestionContent.tsx
  client/components/yeonwoo/AsideEditProfile.tsx
  client/components/yeonwoo/AsideTop.tsx
  client/components/yeonwoo/EditProfile.tsx
  client/components/yeonwoo/SearchBar.tsx
  client/pages/dashboard/[userId]/answers.tsx
  client/pages/dashboard/[userId]/bookmarks.tsx
  client/pages/dashboard/[userId]/index.tsx
  client/pages/membership-withdrawal/index.tsx
  client/pages/questions/index.tsx
Labels: ✨ Feat, [FE] 박연우, 💄 Style

#339 fix : 리뷰태그 한글로 보여지는 부분 오류 수정
  client/components/yeonwoo/AsideBot.tsx
Labels: 🛠 Fix, [FE] 박연우

#340 main : 리뷰태그 오류 수정
  client/components/yeonwoo/AsideBot.tsx
Labels: 🛠 Fix, [FE] 박연우

#342 merge : articleUpload 테스트 추가 로직 작성
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/ArticleDto.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/article/patch/ArticleUpdateTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/article_controller/Update_ArticleController.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/ArticleServiceTest.java
Labels: [BE] 백시온

#343 fix : articleTag 빈 배열일시 에러발생하도록 재수정
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/ArticleDto.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/article/patch/ArticleUpdateTest.java
Labels: [BE] 백시온

#344 oauth 회원가입시 비밀번호 설정 및 성공 후 url 변경
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/security/oauth/CustomOauth2Service.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/security/util/SecurityConstants.java
Labels: [BE] 양은찬, Update ❗️

#341 Loading Component 추가
  client/components/common/Editor.tsx
  client/components/common/Loader.tsx
Labels: [FE] 정하승, 💄 Style

#345 구글 로그인 테스트
  client/components/haseung/LoginForm.tsx
  client/components/haseung/SocialLoginBtn.tsx
  client/pages/_app.tsx
  client/pages/_document.tsx
Labels: ✨ Feat, 🛠 Fix, [FE] 정하승

#346 main : 로딩 컴포넌트, 구글 로그인 테스트
  client/components/common/Editor.tsx
  client/components/common/Loader.tsx
  client/components/haseung/LoginForm.tsx
  client/components/haseung/SocialLoginBtn.tsx
  client/pages/_app.tsx
  client/pages/_document.tsx
Labels: ✨ Feat, [FE] 정하승, 💄 Style

#348 fix : 유저 대시보드에서 리뷰 작성할 경우 배지는 저장하지 않는 문제 수정
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/ReviewService.java
Labels: [BE] 양은찬, 🛠 Fix

#349 구글 url 수정
  client/components/haseung/SocialLoginBtn.tsx
Labels: 🛠 Fix, [FE] 정하승

#351 시큐리티 권한 설정,cors 설정
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/config/WebConfig.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/security/config/SecurityConfig.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/article/post/ArticlePressLikeButton.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/article/post/ReportArticleTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/bookmark/BookmarkTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/comment/CommentTest.java
Labels: [BE] 양은찬, Update ❗️

#350 merge : 게시글 수정 추가 테스트 코드 작성 및 서비스 로직 가독성 상향
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/ArticleService.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/ArticleServiceTest.java
Labels: [BE] 백시온

#347 비밀번호 찾기 기능 구현
  client/components/haseung/LoginForm.tsx
  client/components/haseung/SignUpForm.tsx
  client/pages/find-password/check-auth-code/index.tsx
  client/pages/find-password/get-auth-code/index.tsx
Labels: ✨ Feat, [FE] 정하승, 💄 Style

#353 update : oauth 로그인 시 시큐리티에 필터링되던 문제 수정
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/security/config/SecurityConfig.java
Labels: [BE] 양은찬, Update ❗️

#355 chore : application.yml 로깅레벨 error로 변경
  server/morak_back_end/src/main/resources/application.yml
Labels: [BE] 백시온

#354 type 네이밍 변경, 로딩 컴포넌트 적용 및 수정
  client/components/common/Editor.tsx
  client/components/common/Loader.tsx
  client/components/haseung/LoginForm.tsx
  client/components/haseung/SocialLoginBtn.tsx
  client/libs/interfaces.ts
  client/pages/find-password/check-auth-code/index.tsx
  client/pages/find-password/get-auth-code/index.tsx
Labels: ✨ Feat, [FE] 정하승, 💄 Style

#357 main : type 네이밍 변경, 로딩 컴포넌트 적용 및 수정 (#354)
  client/components/common/Editor.tsx
  client/components/common/Loader.tsx
  client/components/haseung/LoginForm.tsx
  client/components/haseung/SocialLoginBtn.tsx
  client/libs/interfaces.ts
  client/pages/find-password/check-auth-code/index.tsx
  client/pages/find-password/get-auth-code/index.tsx
Labels: ✨ Feat, 🛠 Fix, [FE] 정하승, 💄 Style

#356 대시보드 텍스트 크기 조절, 응원 메시지 모달 오류 수정, 드롭다운/ 개인정보 수정 텍스트 크기 조절 및 인터랙션 전 확인
  client/components/yeonwoo/AsideBot.tsx
  client/components/yeonwoo/AsideEditProfile.tsx
  client/components/yeonwoo/AsideMid.tsx
  client/components/yeonwoo/AsideTop.tsx
  client/components/yeonwoo/BtnDropdown.tsx
  client/components/yeonwoo/CarouselAnswers.tsx
  client/components/yeonwoo/CarouselArticle.tsx
  client/components/yeonwoo/CarouselBookmarks.tsx
  client/components/yeonwoo/CarouselReview.tsx
  client/components/yeonwoo/EditProfile.tsx
  client/pages/dashboard/[userId]/answers.tsx
  client/pages/dashboard/[userId]/bookmarks.tsx
  client/pages/dashboard/[userId]/index.tsx
Labels: ✨ Feat, 🛠 Fix, [FE] 박연우, 💄 Style

#359 로그인 권한 확인 알림, 텍스트 크기 조절, 모달 오류 수정, confirm 추가
  client/components/common/Button.tsx
  client/components/hyejung/AnswerEditor.tsx
  client/components/hyejung/BtnBookmark.tsx
  client/components/hyejung/BtnLike.tsx
  client/components/hyejung/CommentTextArea.tsx
  client/components/hyejung/EditCommentTextArea.tsx
  client/components/yeonwoo/AsideBot.tsx
  client/components/yeonwoo/AsideEditProfile.tsx
  client/components/yeonwoo/AsideMid.tsx
  client/components/yeonwoo/AsideTop.tsx
  client/components/yeonwoo/BtnDropdown.tsx
  client/components/yeonwoo/CarouselAnswers.tsx
  client/components/yeonwoo/CarouselArticle.tsx
  client/components/yeonwoo/CarouselBookmarks.tsx
  client/components/yeonwoo/CarouselReview.tsx
  client/components/yeonwoo/EditProfile.tsx
  client/libs/useCheckIsLogin.ts
  client/pages/ask/index.tsx
  client/pages/dashboard/[userId]/answers.tsx
  client/pages/dashboard/[userId]/bookmarks.tsx
  client/pages/dashboard/[userId]/index.tsx
  client/pages/questions/index.tsx
Labels: ✨ Feat, 🛠 Fix, [FE] 박연우, [FE] 박혜정, 💄 Style

#361 버튼 컴포넌트 onClick props 타입 수정 및 옵셔널로 변경
  client/components/common/Button.tsx
  client/components/hyejung/EditCommentTextArea.tsx
Labels: 🛠 Fix, [FE] 박혜정

#362 카카오 로그인, 버튼 컴포넌트 빌드 오류 수정
  client/components/common/Button.tsx
  client/components/haseung/SocialLoginBtn.tsx
  client/components/hyejung/EditCommentTextArea.tsx
Labels: ✨ Feat, 🛠 Fix, [FE] 정하승, [FE] 박혜정, 💄 Style

#363 update : /answers에 대한 허용 설정 추가
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/security/config/SecurityConfig.java
Labels: [BE] 양은찬, Update ❗️

#364 feat : 리프레시 토큰 갱신 요청 후 에러 발생시 새로고침 하도록 수정
  client/components/hyejung/CommentTextArea.tsx
  client/libs/client.ts
Labels: ✨ Feat, [FE] 박혜정

#366 main : 리프레시 토큰 갱신 요청 후 에러 발생시 새로고침 하도록 수정
  client/components/hyejung/CommentTextArea.tsx
  client/libs/client.ts
Labels: ✨ Feat, Update ❗️, [FE] 박혜정

#365 SEO 작업 및 스타일 수정
  client/components/haseung/SocialLoginBtn.tsx
  client/libs/interfaces.ts
  client/pages/ask/index.tsx
  client/pages/dashboard/[userId]/index.tsx
  client/pages/edit-password/index.tsx
  client/pages/edit-profile/index.tsx
  client/pages/find-password/check-auth-code/index.tsx
  client/pages/find-password/get-auth-code/index.tsx
  client/pages/login/index.tsx
  client/pages/membership-withdrawal/index.tsx
  client/pages/questions/index.tsx
  client/pages/review/index.tsx
  client/pages/signup-email/index.tsx
  client/pages/signup-status/index.tsx
  client/pages/signup/index.tsx
  client/public/favicon.ico
Labels: ✨ Feat, Update ❗️, [FE] 정하승, 💄 Style

#367 Cors 설정 변경, OAuth2 성공 시 리다이렉트 url 변경
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/config/WebConfig.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/security/config/SecurityConfig.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/security/util/SecurityConstants.java
Labels: [BE] 양은찬, Update ❗️

#368 타이틀 수정/적용
  client/components/common/Seo.tsx
  client/libs/interfaces.ts
  client/pages/_app.tsx
  client/pages/ask/index.tsx
  client/pages/dashboard/[userId]/answers.tsx
  client/pages/dashboard/[userId]/bookmarks.tsx
  client/pages/dashboard/[userId]/index.tsx
  client/pages/edit-password/index.tsx
  client/pages/edit-profile/index.tsx
  client/pages/find-password/check-auth-code/index.tsx
  client/pages/find-password/get-auth-code/index.tsx
  client/pages/index.tsx
  client/pages/login/index.tsx
  client/pages/membership-withdrawal/index.tsx
  client/pages/questions/[articleId].tsx
  client/pages/questions/index.tsx
  client/pages/review/completion.tsx
  client/pages/review/index.tsx
  client/pages/review/message.tsx
  client/pages/review/support-morak.tsx
  client/pages/signup-email/index.tsx
  client/pages/signup-status/index.tsx
  client/pages/signup/index.tsx
Labels: ✨ Feat, Update ❗️, [FE] 박연우

#369 oauth 반환값 변경
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/security/oauth/CustomSuccessHandler.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/answer/AnswerPressLikeButton.java
Labels: [BE] 양은찬, Update ❗️

#370 전체 페이지 타이틀, 파비콘 적용
  client/components/common/Seo.tsx
  client/components/haseung/SocialLoginBtn.tsx
  client/pages/_app.tsx
  client/pages/ask/index.tsx
  client/pages/dashboard/[userId]/answers.tsx
  client/pages/dashboard/[userId]/bookmarks.tsx
  client/pages/dashboard/[userId]/index.tsx
  client/pages/edit-password/index.tsx
  client/pages/edit-profile/index.tsx
  client/pages/find-password/check-auth-code/index.tsx
  client/pages/find-password/get-auth-code/index.tsx
  client/pages/index.tsx
  client/pages/login/index.tsx
  client/pages/membership-withdrawal/index.tsx
  client/pages/questions/[articleId].tsx
  client/pages/questions/index.tsx
  client/pages/review/completion.tsx
  client/pages/review/index.tsx
  client/pages/review/message.tsx
  client/pages/review/support-morak.tsx
  client/pages/signup-email/index.tsx
  client/pages/signup-status/index.tsx
  client/pages/signup/index.tsx
  client/public/favicon.ico
Labels: ✨ Feat, 🛠 Fix, Update ❗️, [FE] 박연우, [FE] 정하승

#373 로컬에서 OAuth2 연동 관련 문제 확인하고 모두 수정
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/security/filter/JwtAuthenticationFilter.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/security/oauth/CustomSuccessHandler.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/security/oauth/Oauth2UserDto.java
Labels: [BE] 양은찬, 🛠 Fix

#374 닉네임 validation 추가
  client/components/haseung/SignUpForm.tsx
Labels: ✨ Feat, [FE] 정하승

#372 UI 버그 수정
  client/components/common/Footer.tsx
  client/components/haseung/QuestionList.tsx
  client/components/hyejung/DeveloperLink.tsx
  client/pages/_app.tsx
  client/pages/questions/[articleId].tsx
  client/pages/questions/index.tsx
Labels: ✔️chore, ✨ Feat, [FE] 박혜정, 💄 Style

#371 fix : 대시보드에서 보여주는 응원 메세지 길이 축소
  client/components/yeonwoo/CarouselReview.tsx
Labels: 🛠 Fix, [FE] 박연우, 💄 Style

#375 프로필 수정 닉네임 Validation
  client/components/yeonwoo/AsideTop.tsx
  client/components/yeonwoo/EditProfile.tsx
Labels: ✨ Feat, Update ❗️, [FE] 박연우

#376 쓸모없는 코드 삭제 (window.confirm -> confirm)
  client/components/yeonwoo/BtnDropdown.tsx
  client/components/yeonwoo/EditProfile.tsx
Labels: [FE] 박연우, 🗑 Remove

#377 글 작성 페이지 유효성 검사 등 추가
  client/components/common/Editor.tsx
  client/components/hyejung/AnswerEditor.tsx
  client/components/hyejung/QuillEditor.tsx
  client/pages/ask/index.tsx
Labels: ✔️chore, Update ❗️, [FE] 박혜정

#378 main : 닉네임 생성/수정, 글 작성/수정 Validation, 로딩 컴포넌트 적용
  client/components/common/Editor.tsx
  client/components/common/Footer.tsx
  client/components/haseung/QuestionList.tsx
  client/components/haseung/SignUpForm.tsx
  client/components/hyejung/AnswerEditor.tsx
  client/components/hyejung/DeveloperLink.tsx
  client/components/hyejung/QuillEditor.tsx
  client/components/yeonwoo/AsideTop.tsx
  client/components/yeonwoo/BtnDropdown.tsx
  client/components/yeonwoo/CarouselReview.tsx
  client/components/yeonwoo/EditProfile.tsx
  client/pages/_app.tsx
  client/pages/ask/index.tsx
  client/pages/questions/[articleId].tsx
  client/pages/questions/index.tsx
Labels: ✨ Feat, 🛠 Fix, [FE] 박연우, [FE] 정하승, [FE] 박혜정, 🗑 Remove

#379 merge : 게시글 등록시 articleTag 등록안되는 문제 해결
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/ArticleTag.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/ArticleService.java
Labels: [BE] 백시온

#380 fix : 삭제된 게시글 조회코드 삭제
  client/components/hyejung/QuestionContent.tsx
Labels: 🛠 Fix, [FE] 박혜정

#383 main : 삭제된 게시글 조회코드 삭제
  client/components/hyejung/QuestionContent.tsx
Labels: 🛠 Fix, [FE] 박혜정

#386 유저 권한이 소문자로 적용되는 문제 수정/ 닉네임 글자 제한 수정
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/AuthDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/User.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/util/TestConstants.java
Labels: [BE] 양은찬, 🛠 Fix, Update ❗️

#384 카카오 oAuth 구현
  client/libs/interfaces.ts
  client/pages/oauth/login/index.tsx
Labels: ✨ Feat, [FE] 박혜정

#385 오타, 알림메시지 수정
  client/components/common/Editor.tsx
  client/components/haseung/SearchWithTagButton.tsx
  client/components/hyejung/QuestionContent.tsx
Labels: 🛠 Fix, [FE] 박혜정

#387 main : 카카오 OAuth, 알림 메시지 수정, 태그 오타 수정
  client/components/common/Editor.tsx
  client/components/haseung/SearchWithTagButton.tsx
  client/components/hyejung/QuestionContent.tsx
  client/libs/interfaces.ts
  client/pages/oauth/login/index.tsx
Labels: ✨ Feat, 🛠 Fix, [FE] 박혜정, 💄 Style

#388 update : oauth 로그인 성공 시 리다이렉트 url 변경
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/security/util/SecurityConstants.java
Labels: [BE] 양은찬, Update ❗️

#389 닉네임 정규식 변경/ oauth redirect url 또 또 변경/ 기본 jobtype 설정 및 추가 / 랭킹 조회 시 캐싱하도록 변경
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/config/CacheCosntant.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/config/RedisConfig.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/AuthDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/AvatarDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/PageInfo.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/ResponseMultiplePaging.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/UserDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/User.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/enums/JobType.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/security/util/SecurityConstants.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/auth_user_service/UserService.java
Labels: [BE] 양은찬, Update ❗️

#390 닉네임 정규식 수정, 대시보드 프로필 수정 jobType 추가, jobType 기본값 렌더링 값 지정
  client/components/yeonwoo/AsideTop.tsx
  client/components/yeonwoo/EditProfile.tsx
Labels: ✨ Feat, 🛠 Fix, Update ❗️, [FE] 박연우, 💄 Style

#391 구글 로그인 버튼 제거 / 커스텀 인풋 생성 및 적용
  client/components/common/Editor.tsx
  client/components/common/Input.tsx
  client/components/common/ValildationMsg.tsx
  client/components/haseung/LoginForm.tsx
  client/components/haseung/SignUpForm.tsx
  client/components/haseung/SocialLoginBtn.tsx
  client/pages/oauth/login/index.tsx
Labels: Update ❗️, [FE] 박혜정

#393 main : 정규표현식 수정, OAuth UI 수정, 채용 일정 달력 업데이트, 채용 일정 페이지 생성
  client/components/common/Editor.tsx
  client/components/common/Input.tsx
  client/components/common/ValildationMsg.tsx
  client/components/haseung/LoginForm.tsx
  client/components/haseung/SignUpForm.tsx
  client/components/haseung/SocialLoginBtn.tsx
  client/components/yeonwoo/AsideTop.tsx
  client/components/yeonwoo/Calendar.tsx
  client/components/yeonwoo/EditProfile.tsx
  client/components/yeonwoo/ListLately.tsx
  client/components/yeonwoo/ListRecruit.tsx
  client/components/yeonwoo/Nav.tsx
  client/interfaces.ts
  client/pages/index.tsx
  client/pages/oauth/login/index.tsx
  client/pages/recruit/index.tsx
Labels: ✨ Feat, 🛠 Fix, Update ❗️, [FE] 박연우, [FE] 박혜정, 💄 Style

#394 update : 회원가입 UX 개선
  client/components/haseung/SignUpForm.tsx
  client/pages/signup-email/index.tsx
  client/pages/signup-status/index.tsx
Labels: Update ❗️, [FE] 박연우, 💄 Style, refactor

#395 main : 회원가입 UX 개선
  client/components/haseung/SignUpForm.tsx
  client/pages/signup-email/index.tsx
  client/pages/signup-status/index.tsx
Labels: 🛠 Fix, Update ❗️, [FE] 박연우, 💄 Style, refactor

#396 메인 페이지 UI/UX 개선
  client/components/yeonwoo/AsideTop.tsx
  client/components/yeonwoo/ListLately.tsx
Labels: ✨ Feat, 🛠 Fix, [FE] 박연우, 💄 Style

#397 메인 페이지 UI/UX 개선
  client/components/yeonwoo/AsideTop.tsx
  client/components/yeonwoo/ListLately.tsx
Labels: ✨ Feat, 🛠 Fix, Update ❗️, [FE] 박연우, 💄 Style

#400 fix : 헤더 등급 새로고침시 없어지는 문제 해결
  client/components/yeonwoo/BtnUser.tsx
Labels: 🛠 Fix, [FE] 박연우, 💄 Style

#399 main : 헤더 UI 개선
  client/components/common/Header.tsx
  client/components/yeonwoo/BtnUser.tsx
Labels: Update ❗️, [FE] 박연우, 💄 Style

#401 update : 대시보드 태그 disabled 설정
  client/components/yeonwoo/AsideBot.tsx
  client/components/yeonwoo/AsideMid.tsx
Labels: Update ❗️, [FE] 박연우, 💄 Style

#403 유저 대시보드 잔디 json 반환값 추가 , 관련 테스트 수정, 캐시 적용으로 인해 깨지는 테스트 임시 주석처리
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/dto/ActivityDto.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/auth_user_service/UserService.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/user/getUserRankTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/user_controller/DashboardTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/user_service/getUserDashboardTest.java
Labels: [BE] 양은찬, ✅ Test, Update ❗️

#405 캘린더 조회 날짜 범위를 조회일자에 해당되는 달로 수정 및 관련 테스트 수정
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/repository/JobQueryRepository.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/CalendarService.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/calendar/CalendarTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/repository/JobQueryRepositoryTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/service/CalendarServiceTest.java
Labels: [BE] 양은찬, Update ❗️

#407 정보글 목록 페이지
  client/components/yeonwoo/InformsList.tsx
  client/pages/informations/index.tsx
Labels: ✨ Feat, [FE] 박연우, 💄 Style

#406 프로필 수정시 닉네임 중복검사
  client/components/yeonwoo/AsideTop.tsx
  client/components/yeonwoo/EditProfile.tsx
  client/libs/inspectNicknameDuplication.ts
Labels: ✨ Feat, [FE] 박연우

#409 정보 게시글 상세페이지 구현
  client/components/hyejung/QuestionContent.tsx
  client/components/hyejung/QuestionMainText.tsx
  client/pages/informations/[articleId].tsx
  client/pages/questions/[articleId].tsx
Labels: ✨ Feat, [FE] 박혜정

#410 react-toastify,react-confirm-alert 적용
  client/components/common/Editor.tsx
  client/components/haseung/LoginForm.tsx
  client/components/haseung/SignUpForm.tsx
  client/package-lock.json
  client/package.json
  client/pages/_app.tsx
  client/pages/find-password/check-auth-code/index.tsx
  client/pages/find-password/get-auth-code/index.tsx
  client/pages/signup-email/index.tsx
Labels: ✨ Feat, [FE] 정하승, 💄 Style

#411 불필요한 파일 삭제 및 toast 컴포넌트 추가
  client/components/haseung/EditPasswordForm.tsx
  client/components/haseung/LoadMoreButton.tsx
  client/pages/ask/index.tsx
Labels: ✔️chore, ✨ Feat, [FE] 정하승

#414 feat : 좋아요, 북마크 여부 확인을 위한 데이터 요청 로직 추가
  client/components/hyejung/QuestionContent.tsx
Labels: ✨ Feat, [FE] 박혜정

#416 Fix : 리프레시 토큰 만료 후 무한로딩 현상 해결
  client/libs/client.ts
  client/libs/tokens.ts
Labels: ✨ Feat, 🛠 Fix, [FE] 박혜정

#417 fix : 메소드 명 수정
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/controller/ArticleController.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Answer.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Article.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/ArticleTag.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Avatar.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Comment.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/File.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Notification.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Report.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/Review.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/entity/User.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/AnswerService.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/ArticleService.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/CommentService.java
  server/morak_back_end/src/main/java/com/morakmorak/morak_back_end/service/ReviewService.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/article/get/ArticleGetTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/review/PostReviewTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/user/UserTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/Integration/user/getUserRankTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/controller/article_controller/searchArticleTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/entity/UserTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/mapper/ArticleMapperTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/mapper/UserMapperTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/repository/ArticleQueryRepositoryImplTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/repository/answer_repository/AnswerQueryRepositoryTest.java
  server/morak_back_end/src/test/java/com/morakmorak/morak_back_end/repository/user_repository/UserRepositoryTest.java
Labels: [BE] 백시온
