Repository codestates-seb/seb40_main_004, pull requests merged in 2023-02, with the labels that each got.

#449 코멘트 리스트 컴포넌트 리팩토링
  client/components/questions/question-detail/AnswerContent/index.tsx
  client/components/questions/question-detail/AnswerContent/useAnswerContent.ts
  client/components/questions/question-detail/Comment/Comment.tsx
  client/components/questions/question-detail/Comment/CommentTextArea.tsx
  client/components/questions/question-detail/Comment/EditCommentTextArea.tsx
  client/components/questions/question-detail/Comment/index.tsx
  client/components/questions/question-detail/Comment/useComment.ts
  client/components/questions/question-detail/QuestionContent/QuestionContent.tsx
Labels: [FE] 박혜정, refactor

#447 유저 인증 api 호출 코드 분리, 필드 값 실시간 감지
  client/api/authCheckAndSetCodeApi.ts
  client/api/loginApi.ts
  client/api/makePostRequest.ts
  client/api/signUpApi.ts
  client/components/common/Input.tsx
  client/components/login/LoginForm/index.tsx
  client/components/signup/SignupForm/index.tsx
  client/pages/find-password/check-auth-code/index.tsx
  client/pages/find-password/get-auth-code/index.tsx
  client/pages/find-password/useCheckAuth.tsx
  client/pages/signup-email/index.tsx
Labels: ✨ Feat, [FE] 정하승, refactor

#454 useCheckAuth export 방식 변경 및 hooks 폴더로 이동
  client/components/signup/SignupForm/index.tsx
  client/hooks/useCheckAuth.ts
  client/pages/find-password/check-auth-code/index.tsx
  client/pages/find-password/get-auth-code/index.tsx
Labels: 🛠 Fix, [FE] 정하승

#459 refactor : 액세스 토큰 갱신로직 수정
  client/libs/client.ts
Labels: [FE] 박혜정, refactor

#460 api 로직 변경, 스타일 수정
  client/api/makePostRequest.ts
  client/api/signUpApi.ts
  client/components/common/SocialLoginBtn.tsx
  client/pages/_app.tsx
  client/pages/_document.tsx
  client/pages/find-password/check-auth-code/index.tsx
  client/pages/find-password/get-auth-code/index.tsx
Labels: ✔️chore, ✨ Feat, 🛠 Fix, [FE] 정하승, 💄 Style

#461 타입 지정, toastify 적용
  client/components/common/Header/Logo.tsx
  client/components/common/QuillEditor/Editor.tsx
  client/components/edit-privacy/EditAvatar.tsx
  client/components/edit-privacy/EditProfile.tsx
  client/components/main/HallOfFame.tsx
  client/components/questions/question-detail/AnswerContent/AnswerContainer.tsx
  client/components/questions/question-detail/AnswerContent/AnswerEditor.tsx
  client/components/questions/question-detail/AnswerContent/index.tsx
  client/components/questions/question-detail/QuestionContent/QuestionContent.tsx
  client/pages/edit-password/index.tsx
  client/pages/edit-profile/index.tsx
  client/pages/review/completion.tsx
Labels: ✔️chore, [FE] 정하승

#468 게시글 상세페이지 질문, 답변 컴포넌트 코드 리팩토링입니다.
  client/api/aritlceApi.ts
  client/components/common/BtnLike.tsx
  client/components/questions/QuestionList/index.tsx
  client/components/questions/question-detail/AnswerContent/AnswerContainer.tsx
  client/components/questions/question-detail/AnswerContent/index.tsx
  client/components/questions/question-detail/QuestionContent/BtnBookmark.tsx
  client/components/questions/question-detail/QuestionContent/QuestionContent.tsx
  client/components/questions/question-detail/QuestionContent/useHandleClickBookmark.ts
  client/components/questions/question-detail/QuestionContent/useQuestionContent.ts
  client/hooks/useGetArticleId.ts
  client/libs/getConfirmAlert.ts
  client/pages/questions/[articleId].tsx
Labels: 🛠 Fix, [FE] 박혜정, refactor

#470 메인 페이지 최근 게시글 10개 항목 디자인 수정
  client/components/main/ListLately.tsx
  client/pages/index.tsx
Labels: [FE] 박혜정, 💄 Style

#469 회원가입 페이지 label 추가, 비밀번호 확인 검증 로직 추가
  client/components/common/Input.tsx
  client/components/edit-privacy/CancelButton.tsx
  client/components/edit-privacy/EditProfile.tsx
  client/components/signup/SignupForm/index.tsx
Labels: ✨ Feat, 🛠 Fix, [FE] 정하승, 💄 Style, refactor
