Repository codestates-seb/seb40_main_004, pull requests merged in 2023-01, with the labels that each got.

#422 refactor : 컴포넌트 별로 폴더 및 파일 분리
  client/components/common/Button.tsx
  client/components/common/Footer/DeveloperLink.tsx
  client/components/common/Footer/index.tsx
  client/components/common/Header/BtnDropdown.tsx
  client/components/common/Header/BtnLogin.tsx
  client/components/common/Header/BtnUser.tsx
  client/components/common/Header/Logo.tsx
  client/components/common/Header/Nav.tsx
  client/components/common/Header/SearchBar.tsx
  client/components/common/Header/index.tsx
  client/components/common/MorakLogo.tsx
  client/components/common/Pagination.tsx
  client/components/common/QuillEditor/Editor.tsx
  client/components/common/QuillEditor/Select.tsx
  client/components/common/QuillEditor/index.tsx
  client/components/common/SocialLoginBtn.tsx
  client/components/hyejung/AnswerEditor.tsx
  client/components/informations/InformsList/index.tsx
  client/components/login/LoginForm/index.tsx
  client/components/main/Calendar.tsx
  client/components/main/CarouselMain.tsx
  client/components/main/CheerUp.tsx
  client/components/main/HallOfFame.tsx
  client/components/main/ListLately.tsx
  client/components/questions/QuestionList/index.tsx
  client/components/questions/SearchWithTagButton/index.tsx
  client/components/signup/SignupForm/Divider.tsx
  client/components/signup/SignupForm/index.tsx
  client/pages/index.tsx
  client/pages/informations/[articleId].tsx
  client/pages/informations/index.tsx
  client/pages/login/index.tsx
  client/pages/post/index.tsx
  client/pages/questions/index.tsx
  client/pages/signup/index.tsx
Labels: [FE] 정하승, [FE] 박혜정, refactor

#423 refactor : 컴포넌트 별로 폴더 및 파일 분리
  client/components/common/BtnLike.tsx
  client/components/common/BtnTag.tsx
  client/components/common/CreatedDate.tsx
  client/components/common/TagList.tsx
  client/components/common/UserNickname.tsx
  client/components/dashboard/AsideBot.tsx
  client/components/dashboard/AsideMid.tsx
  client/components/dashboard/AsideTop.tsx
  client/components/dashboard/CarouselAnswers.tsx
  client/components/dashboard/CarouselArticle.tsx
  client/components/dashboard/CarouselBookmarks.tsx
  client/components/dashboard/CarouselReview.tsx
  client/components/dashboard/Grass.tsx
  client/components/edit-privacy/AsideEditProfile.tsx
  client/components/edit-privacy/EditAvatar.tsx
  client/components/edit-privacy/EditProfile.tsx
  client/components/haseung/Intro.tsx
  client/components/hyejung/QuestionTitle.tsx
  client/components/login/LoginForm/index.tsx
  client/components/questions/question-detail/AnswerContent/AnswerContainer.tsx
  client/components/questions/question-detail/AnswerContent/AnswerEditor.tsx
  client/components/questions/question-detail/AnswerContent/AnswerMainText.tsx
  client/components/questions/question-detail/AnswerContent/ProfileImage.tsx
  client/components/questions/question-detail/AnswerContent/index.tsx
  client/components/questions/question-detail/CommentContainer/Comment.tsx
  client/components/questions/question-detail/CommentContainer/CommentContainer.tsx
  client/components/questions/question-detail/CommentContainer/CommentTextArea.tsx
  client/components/questions/question-detail/CommentContainer/EditCommentTextArea.tsx
  client/components/questions/question-detail/QuestionContent/BtnBookmark.tsx
  client/components/questions/question-detail/QuestionContent/QuestionContent.tsx
  client/components/questions/question-detail/QuestionContent/QuestionMainText.tsx
  client/components/reqruit/ListRecruit.tsx
  client/components/review/BtnBackArticle.tsx
  client/components/review/ProgressBar.tsx
  client/components/review/ReviewTag.tsx
  client/components/signup-email/AuthenticationTimer.tsx
  client/components/signup/SignupForm/Divider.tsx
  client/pages/dashboard/[userId]/answers.tsx
  client/pages/dashboard/[userId]/bookmarks.tsx
  client/pages/dashboard/[userId]/index.tsx
  client/pages/edit-password/index.tsx
  client/pages/edit-profile/index.tsx
  client/pages/informations/[articleId].tsx
  client/pages/membership-withdrawal/index.tsx
  client/pages/questions/[articleId].tsx
  client/pages/recruit/index.tsx
  client/pages/review/completion.tsx
  client/pages/review/index.tsx
  client/pages/review/message.tsx
  client/pages/review/support-morak.tsx
  client/pages/signup-email/index.tsx
  client/pages/signup/index.tsx
Labels: [FE] 정하승, [FE] 박혜정, refactor

#425 refactor : atom 분리
  client/atoms/answerAtom.ts
  client/atoms/articleAtom.ts
  client/atoms/commentAtom.ts
  client/atoms/keywordAtom.ts
  client/atoms/loginAtom.ts
  client/atoms/renderingAtom.ts
  client/atoms/reviewAtom.ts
  client/atoms/userAtom.ts
  client/atomsHS.ts
  client/components/common/BtnLike.tsx
  client/components/common/Header/BtnDropdown.tsx
  client/components/common/Header/BtnUser.tsx
  client/components/common/Header/SearchBar.tsx
  client/components/common/Header/index.tsx
  client/components/common/Pagination.tsx
  client/components/common/QuillEditor/Editor.tsx
  client/components/dashboard/AsideTop.tsx
  client/components/edit-privacy/EditAvatar.tsx
  client/components/edit-privacy/EditProfile.tsx
  client/components/login/LoginForm/index.tsx
  client/components/questions/question-detail/AnswerContent/AnswerEditor.tsx
  client/components/questions/question-detail/AnswerContent/index.tsx
  client/components/questions/question-detail/CommentContainer/Comment.tsx
  client/components/questions/question-detail/CommentContainer/CommentContainer.tsx
  client/components/questions/question-detail/CommentContainer/CommentTextArea.tsx
  client/components/questions/question-detail/QuestionContent/BtnBookmark.tsx
  client/components/questions/question-detail/QuestionContent/QuestionContent.tsx
  client/components/review/ReviewTag.tsx
  client/components/signup/SignupForm/index.tsx
  client/kakaoinit.ts
  client/libs/useCheckIsLogin.ts
  client/pages/informations/index.tsx
  client/pages/oauth/login/index.tsx
  client/pages/post/index.tsx
  client/pages/questions/[articleId].tsx
  client/pages/questions/index.tsx
  client/pages/review/completion.tsx
  client/pages/review/index.tsx
  client/pages/review/message.tsx
  client/pages/review/support-morak.tsx
  client/pages/signup-email/index.tsx
Labels: [FE] 정하승, [FE] 박혜정, refactor

#435 리다이렉트 경로 수정, 문구 변경, 인터페이스 분리
  client/components/questions/question-detail/QuestionContent/QuestionContent.tsx
  client/pages/informations/index.tsx
  client/types/answer.ts
  client/types/article.ts
  client/types/base.ts
  client/types/comment.ts
Labels: ✔️chore, ✨ Feat, 🛠 Fix, [FE] 정하승, [FE] 박혜정

#442 toast 컴포넌트 색상 변경, 카카오 uri 수정, 로딩 컴포넌트 위치 변경
  client/components/common/SocialLoginBtn.tsx
  client/components/dashboard/AsideTop.tsx
  client/pages/find-password/check-auth-code/index.tsx
  client/pages/find-password/get-auth-code/index.tsx
Labels: 🛠 Fix, [FE] 정하승, 💄 Style

#443 Modify : 에러 확인을 위해 임시 주석처리
  client/libs/client.ts
Labels: [FE] 박혜정
