Repository codestates-seb/seb40_main_004, pull requests merged in 2023-03, with the labels that each got.

#477 fix : 채용 일정 요청 방식 수정
  client/components/common/Header/Nav.tsx
  client/components/recruit/ListRecruit.tsx
Labels: 🛠 Fix, [FE] 박혜정

#478 네비게이션 바 반응형 1차 작업 및 컴포넌트,함수 분리
  client/components/common/Header/BtnLogin.tsx
  client/components/common/Header/BtnUser.tsx
  client/components/common/Header/Logo.tsx
  client/components/common/Header/Nav.tsx
  client/components/common/Header/index.tsx
  client/components/common/QuillEditor/Editor.tsx
  client/components/common/QuillEditor/EditorLabel.tsx
  client/components/common/QuillEditor/FormButtonGroup.tsx
  client/components/common/QuillEditor/TitleInputBox.tsx
  client/components/signup/SignupForm/AccountLink.tsx
  client/components/signup/SignupForm/RegistrationButton.tsx
  client/components/signup/SignupForm/index.tsx
  client/libs/tagOptions.ts
  client/tailwind.config.js
Labels: [FE] 정하승, 💄 Style, refactor

#479 게시글 신고 기능 구현하였습니다.
  client/api/aritlceApi.ts
  client/components/questions/question-detail/QuestionContent/QuestionContent.tsx
  client/components/questions/question-detail/QuestionContent/ReportModal.tsx
  client/components/questions/question-detail/QuestionContent/useQuestionContent.ts
  client/types/article.ts
Labels: [BE] 백시온, ✨ Feat, [FE] 박혜정

#492 fix : 데이터 통신 실패시 예외처리
  client/components/main/HallOfFame.tsx
  client/components/main/ListLately.tsx
  client/components/recruit/ListRecruit.tsx
  client/pages/recruit/index.tsx
Labels: 🛠 Fix, [FE] 박혜정

#500 프로필 수정 코드 수정, 썸네일 안보이는 현상 수정
  client/components/edit-privacy/ChangeButton.tsx
  client/components/edit-privacy/EditProfile.tsx
  client/components/edit-privacy/NewPasswordInput.tsx
  client/components/edit-privacy/NewPaswordCheckInput.tsx
  client/components/edit-privacy/OriginalPasswordInput.tsx
  client/components/edit-privacy/ProfileEditTitle.tsx
  client/components/edit-privacy/SaveButton.tsx
  client/components/edit-privacy/SelectJobOption.tsx
  client/components/edit-privacy/WithDrawalButton.tsx
  client/libs/jobOptions.ts
  client/pages/_app.tsx
Labels: 🛠 Fix, [FE] 정하승, 💄 Style, refactor
